import { count, eq } from "drizzle-orm";

import { db, postgresClient } from "@/lib/db";
import { ankerPowerBankRows } from "@/lib/db/anker-power-bank-seed";
import { equipment, equipmentCategories, manufacturers } from "@/lib/db/schema";
import { ugreenPowerBankRows } from "@/lib/db/ugreen-power-bank-seed";

const categories = [
  {
    slug: "power-banks",
    name: "Power Banks",
    nameUk: "Павербанки",
    description:
      "Portable USB and DC battery packs for phones, laptops, and field kits.",
    descriptionUk:
      "Портативні USB та DC акумулятори для телефонів, ноутбуків і польових комплектів.",
  },
  {
    slug: "power-stations",
    name: "Power Stations",
    nameUk: "Портативні електростанції",
    description:
      "Portable AC power stations for backup power, camping, and light jobsite use.",
    descriptionUk:
      "Портативні AC електростанції для резервного живлення, кемпінгу та легких робочих задач.",
  },
  {
    slug: "batteries",
    name: "Batteries",
    nameUk: "Акумулятори",
    description:
      "Standalone battery modules for off-grid, hybrid, and backup systems.",
    descriptionUk:
      "Окремі акумуляторні модулі для автономних, гібридних і резервних систем.",
  },
  {
    slug: "inverters",
    name: "Inverters",
    nameUk: "Інвертори",
    description: "Grid-tie, off-grid, and hybrid inverters for energy systems.",
    descriptionUk:
      "Мережеві, автономні та гібридні інвертори для енергетичних систем.",
  },
] as const;

const manufacturerRows = [
  { name: "Anker", country: "United States" },
  { name: "Bluetti", country: "United States" },
  { name: "EcoFlow", country: "United States" },
  { name: "Growatt", country: "China" },
  { name: "Renogy", country: "United States" },
  { name: "Victron Energy", country: "Netherlands" },
  { name: "Pylontech", country: "China" },
  { name: "Zendure", country: "United States" },
  { name: "Xiaomi", country: "China" },
  { name: "Unbranded", country: null },
  { name: "EVE", country: "China" },
  { name: "REPT", country: "China" },
  { name: "UGREEN", country: "China" },
] as const;

type SeedEquipment = {
  categorySlug: (typeof categories)[number]["slug"];
  manufacturer: (typeof manufacturerRows)[number]["name"];
  model: string;
  slug: string;
  summary: string;
  summaryUk: string;
  imagePath: string;
  priceCents?: number | null;
  productCode?: string;
  nominalVoltageV?: number;
  capacityWh?: number;
  continuousPowerW?: number;
  peakPowerW?: number;
  maxPvVoltageV?: number;
  maxChargeCurrentA?: number;
  chemistry?: string;
  communicationProtocols?: string;
  weightGrams?: number;
  warrantyYears?: number;
  lifecycleCycles?: number;
  sourceLabel: string;
  sourceLabelUk: string;
  sourceUrl?: string;
  specifications?: Record<string, unknown>;
};

const equipmentRows: SeedEquipment[] = [
  {
    categorySlug: "power-banks",
    manufacturer: "Xiaomi",
    model: "UltraThin Magnetic Power Bank 5000 15W",
    slug: "xiaomi-ultrathin-magnetic-power-bank-5000-15w",
    summary:
      "Ultra-slim magnetic power bank with 15 W wireless charging, 22.5 W USB-C output, and two-device charging.",
    summaryUk:
      "Ultra-slim magnetic power bank with 15 W wireless charging, 22.5 W USB-C output, and two-device charging.",
    imagePath:
      "https://media.vladyka.dev/power-bank/xiaomi/39c0de98f9e4ab7d06e0660e3a34bd9a.png",
    priceCents: null,
    productCode: "MDY-20-EB",
    nominalVoltageV: 5,
    capacityWh: 19,
    continuousPowerW: 23,
    peakPowerW: 23,
    maxChargeCurrentA: 3,
    chemistry: "Lithium-ion",
    weightGrams: 98,
    sourceLabel: "Xiaomi official specs",
    sourceUrl:
      "https://www.mi.com/global/product/xiaomi-ultrathin-magnetic-power-bank-5000-15w/specs/",
    specifications: {
      ratedCapacityMah: 3000,
      ratedCapacityAt: "5V/2A",
      ratedEnergyWh: 18.58,
      typicalEnergyWh: 18.95,
      typicalCapacityMah: 5000,
      batteryVoltageV: 3.79,
      maxOutputW: 22.5,
      wirelessOutputW: 15,
      iphoneWirelessOutputW: 7.5,
      simultaneousOutput: "USB-C 5V/1.5A 7.5W max + wireless 5W max",
      dimensionsMm: "98.5 x 71.5 x 6",
      operatingFrequencyKhz: "120-147",
      wirelessChargingMechanism: "Magnetic induction",
      outputPorts: ["USB-C", "Wireless magnetic charging"],
      features: [
        "6 mm thin body",
        "Aluminium alloy shell",
        "Dual-NTC temperature control",
        "Ten layers of safety protection",
        "Air-travel suitable under 100 Wh",
      ],
      compatibleDeviceFamilies: [
        "Xiaomi 12-15 series",
        "iPhone 12-17 series",
        "Samsung Galaxy S23-S25",
        "Google Pixel 9-10",
      ],
      packageContents: ["Power bank", "User manual", "Warranty card"],
      listPosition: 1,
    },
    sourceLabelUk: "Xiaomi official specs",
  },
  {
    categorySlug: "power-banks",
    manufacturer: "Xiaomi",
    model: "Magnetic Power Bank 10000 with Built-in Stand",
    slug: "xiaomi-magnetic-power-bank-10000-with-built-in-stand",
    summary:
      "Magnetic 10,000 mAh-class bank with an adjustable stand, integrated USB-C cable, display, and three-device charging.",
    summaryUk:
      "Magnetic 10,000 mAh-class bank with an adjustable stand, integrated USB-C cable, display, and three-device charging.",
    imagePath:
      "https://media.vladyka.dev/power-bank/xiaomi/f857732c9d6f01ad11b20280c57783ea.png",
    priceCents: null,
    productCode: "WPB1007Z",
    nominalVoltageV: 5,
    capacityWh: 37,
    continuousPowerW: 33,
    peakPowerW: 33,
    maxChargeCurrentA: 3,
    chemistry: "Lithium-ion",
    weightGrams: 229,
    communicationProtocols: "BC1.2, PD2.0, PD3.0 PPS, QC2.0, QC3.0, Apple 2.4A",
    sourceLabel: "Xiaomi official specs",
    sourceUrl:
      "https://www.mi.com/global/product/xiaomi-magnetic-power-bank-10000-with-built-in-stand/specs/",
    specifications: {
      ratedCapacityMah: 5900,
      ratedCapacityAt: "5V/3A",
      ratedEnergyWh: 37,
      typicalCapacityMah: 10000,
      batteryVoltageV: 7.4,
      maxInputW: 30,
      maxOutputW: 33,
      wirelessOutputW: 15,
      simultaneousOutput: "15W max wired and wireless",
      dimensionsMm: "108.8 x 68.9 x 20.25",
      inputPorts: ["Integrated USB-C cable", "USB-C"],
      outputPorts: [
        "Integrated USB-C cable",
        "USB-C",
        "Wireless magnetic charging",
      ],
      chargingProtocols: [
        "BC1.2",
        "PD2.0",
        "PD3.0 PPS",
        "QC2.0",
        "QC3.0",
        "Apple 2.4A",
      ],
      features: [
        "Adjustable built-in stand opens to about 80 degrees",
        "13N magnetic force",
        "Digital display",
        "Pass-through charging",
        "Nine layers of safety protection",
      ],
      packageContents: [
        "Xiaomi Magnetic Power Bank 10000 with Built-in Stand",
        "User manual",
      ],
      listPosition: 2,
    },
    sourceLabelUk: "Xiaomi official specs",
  },
  {
    categorySlug: "power-banks",
    manufacturer: "Xiaomi",
    model: "67W Power Bank 10000 (Integrated Cable)",
    slug: "xiaomi-67w-power-bank-10000-integrated-cable",
    summary:
      "Fast 67 W USB-C power bank with integrated cable, 65 W self-charging, USB-A output, display, and pass-through charging.",
    summaryUk:
      "Fast 67 W USB-C power bank with integrated cable, 65 W self-charging, USB-A output, display, and pass-through charging.",
    imagePath:
      "https://media.vladyka.dev/power-bank/xiaomi/686a0afb4f10204d55178271808a738e.png",
    priceCents: null,
    productCode: "PB1067",
    nominalVoltageV: 5,
    capacityWh: 39,
    continuousPowerW: 67,
    peakPowerW: 67,
    maxChargeCurrentA: 3,
    chemistry: "Lithium-ion",
    weightGrams: 247,
    sourceLabel: "Xiaomi official specs",
    sourceUrl:
      "https://www.mi.com/global/product/xiaomi-67w-power-bank-10000-integrated-cable/specs/",
    specifications: {
      ratedCapacityMah: 6000,
      ratedCapacityAt: "5V/3A",
      ratedEnergyWh: 39.48,
      batteryCells: "Three 3400mAh cells",
      batteryVoltageV: 11.61,
      maxInputW: 65,
      maxOutputW: 67,
      dimensionsMm: "115 x 66 x 26 excluding integrated cable",
      operatingTemperatureC: "5 to 35",
      chargingTime: [
        "Approx. 1.9h with 9V/3A charger",
        "Approx. 1.3h with 20V/3.25A charger",
      ],
      inputPorts: ["Integrated USB-C cable", "USB-C"],
      outputPorts: ["Integrated USB-C cable", "USB-C", "USB-A"],
      features: [
        "Charge three devices simultaneously",
        "Pass-through charging",
        "Digital display",
        "9 safety features",
        "Air-travel suitable under 100 Wh",
      ],
      packageContents: [
        "Xiaomi 67W Power Bank 10000 (Integrated Cable)",
        "User manual",
        "Warranty card",
      ],
      listPosition: 3,
    },
    sourceLabelUk: "Xiaomi official specs",
  },
  {
    categorySlug: "power-banks",
    manufacturer: "Xiaomi",
    model: "67W Power Bank 20000 (Integrated Cable)",
    slug: "xiaomi-67w-power-bank-20000-integrated-cable",
    summary:
      "Higher-capacity 67 W power bank with integrated USB-C cable, USB-C and USB-A ports, and 65 W self-charging.",
    summaryUk:
      "Higher-capacity 67 W power bank with integrated USB-C cable, USB-C and USB-A ports, and 65 W self-charging.",
    imagePath:
      "https://media.vladyka.dev/power-bank/xiaomi/78d1b5791d5ac17aee35cf143b53580d.png",
    priceCents: null,
    productCode: "PB2067",
    nominalVoltageV: 5,
    capacityWh: 74,
    continuousPowerW: 67,
    peakPowerW: 67,
    maxChargeCurrentA: 3,
    chemistry: "Lithium-ion",
    weightGrams: 415,
    sourceLabel: "Xiaomi official specs",
    sourceLabelUk: "Xiaomi official specs",
    sourceUrl:
      "https://www.mi.com/global/product/xiaomi-67w-power-bank-20000-integrated-cable/specs/",
    specifications: {
      ratedCapacityMah: 12000,
      ratedCapacityAt: "5V/3A",
      ratedEnergyWh: 74.37,
      batteryVoltageV: 11.1,
      batteryCapacityMahAtVoltage: 6700,
      typicalCapacityMah: 20000,
      maxInputW: 65,
      maxOutputW: 67,
      dimensionsMm: "140 x 72 x 31.2",
      inputPorts: ["Integrated USB-C cable", "USB-C"],
      outputPorts: ["Integrated USB-C cable", "USB-C", "USB-A"],
      features: [
        "67W max fast output",
        "65W max high-speed self-charging",
        "Integrated USB-C cable",
        "Multi-port output",
        "Air-travel suitable under 100 Wh",
      ],
      packageContents: [
        "Xiaomi 67W Power Bank 20000 (Integrated Cable)",
        "User manual",
      ],
      listPosition: 4,
    },
  },
  {
    categorySlug: "power-banks",
    manufacturer: "Xiaomi",
    model: "Super Slim Magnetic Power Bank 5000",
    slug: "xiaomi-super-slim-magnetic-power-bank-5000",
    summary:
      "Slim magnetic 5,000 mAh power bank with aluminium body, USB-C input/output, and up to 22.5 W wired output.",
    summaryUk:
      "Slim magnetic 5,000 mAh power bank with aluminium body, USB-C input/output, and up to 22.5 W wired output.",
    imagePath:
      "https://media.vladyka.dev/power-bank/xiaomi/daad9ee33362ca155392459e09c9b996.png",
    priceCents: null,
    productCode: "WPB0507S",
    nominalVoltageV: 5,
    capacityWh: 19,
    continuousPowerW: 23,
    peakPowerW: 23,
    maxChargeCurrentA: 3,
    chemistry: "Lithium-ion",
    weightGrams: 122,
    sourceLabel: "Xiaomi official specs",
    sourceLabelUk: "Xiaomi official specs",
    sourceUrl:
      "https://www.mi.com/global/product/xiaomi-super-slim-magnetic-power-bank-5000/specs/",
    specifications: {
      ratedCapacityMah: 3000,
      ratedCapacityAt: "5V",
      ratedEnergyWh: 19.35,
      typicalCapacityMah: 5000,
      batteryVoltageV: 3.87,
      maxInputW: 20,
      maxOutputW: 22.5,
      dimensionsMm: "102 x 69.6 x 8.7",
      inputPorts: ["USB-C"],
      outputPorts: ["USB-C", "Wireless magnetic charging"],
      features: [
        "Approx. 8.7 mm thick",
        "Meticulously crafted aluminium body",
        "USB-C wired output up to 22.5W",
      ],
      packageContents: [
        "Xiaomi Super Slim Magnetic Power Bank 5000",
        "USB-C to USB-C charging cable",
        "User manual",
      ],
      listPosition: 5,
    },
  },
  {
    categorySlug: "power-banks",
    manufacturer: "Xiaomi",
    model: "33W Magnetic Power Bank 10000 (Integrated Cable)",
    slug: "xiaomi-33w-magnetic-power-bank-10000-integrated-cable",
    summary:
      "Magnetic 10,000 mAh-class power bank with integrated USB-C cable, 33 W wired output, 7.5 W wireless output, and dual USB-C charging.",
    summaryUk:
      "Magnetic 10,000 mAh-class power bank with integrated USB-C cable, 33 W wired output, 7.5 W wireless output, and dual USB-C charging.",
    imagePath:
      "https://i02.appmifile.com/962_operatorx_operatorx_opx/28/04/2025/f24a4499d06863897ff5fba58a39eeab.png",
    priceCents: null,
    productCode: "WPB1007MI",
    nominalVoltageV: 5,
    capacityWh: 37,
    continuousPowerW: 33,
    peakPowerW: 33,
    maxChargeCurrentA: 3,
    chemistry: "Lithium-ion",
    weightGrams: 238,
    communicationProtocols: "USB-C PD, magnetic wireless charging",
    sourceLabel: "Xiaomi official specs",
    sourceLabelUk: "Xiaomi official specs",
    sourceUrl:
      "https://www.mi.com/global/product/xiaomi-33w-magnetic-power-bank-10000-integrated-cable/specs/",
    specifications: {
      ratedCapacityMah: 5900,
      ratedCapacityAt: "5V/3A",
      ratedEnergyWh: 37,
      batteryCells: "Two 5000mAh batteries",
      maxInputW: 30,
      maxOutputW: 33,
      wirelessOutputW: 7.5,
      multiPortOutput: "5V/3A 15W max",
      dimensionsMm: "109 x 68.5 x 19.8",
      inputPorts: ["Integrated USB-C cable", "USB-C"],
      outputPorts: ["Integrated USB-C cable", "USB-C"],
      inputParameters: [
        "Integrated USB-C cable: 5V/3A, 9V/3A, 12V/2.5A",
        "USB-C: 5V/3A, 9V/3A, 12V/2.5A",
      ],
      outputParameters: [
        "Integrated USB-C cable: 5V/3A, 9V/3A, 11V/3A, 12V/2.5A, 15V/2A, 33W max",
        "USB-C: 5V/3A, 9V/3A, 11V/3A, 12V/2.5A, 15V/2A, 33W max",
      ],
      packageContents: [
        "Xiaomi 33W Magnetic Power Bank 10000 (Integrated Cable)",
        "User manual",
        "Warranty card",
      ],
      listPosition: 6,
    },
  },
  {
    categorySlug: "power-banks",
    manufacturer: "Xiaomi",
    model: "Power Bank 20000 (Integrated Cable)",
    slug: "xiaomi-power-bank-20000-integrated-cable",
    summary:
      "20,000 mAh-class power bank with integrated USB-C cable, USB-C and USB-A outputs, and 22.5 W multi-port output.",
    summaryUk:
      "20,000 mAh-class power bank with integrated USB-C cable, USB-C and USB-A outputs, and 22.5 W multi-port output.",
    imagePath:
      "https://i02.appmifile.com/914_operatorx_operatorx_opx/25/04/2025/677c16b0f8e1a8553c1657f16f4d6037.png",
    priceCents: null,
    productCode: "PB2020MI",
    nominalVoltageV: 5,
    capacityWh: 74,
    continuousPowerW: 23,
    peakPowerW: 23,
    maxChargeCurrentA: 3,
    chemistry: "Lithium-ion",
    weightGrams: 342,
    sourceLabel: "Xiaomi official specs",
    sourceLabelUk: "Xiaomi official specs",
    sourceUrl:
      "https://www.mi.com/global/product/xiaomi-power-bank-20000/specs/",
    specifications: {
      ratedCapacityMah: 13000,
      ratedCapacityAt: "5V",
      ratedEnergyWh: 74,
      typicalCapacityMah: 20000,
      batteryVoltageV: 3.7,
      ratedCapacitiesByVoltage: {
        "5V": "13Ah",
        "9V": "7.5Ah",
        "10V": "6.7Ah",
        "12V": "5.6Ah",
      },
      maxInputW: 22.5,
      maxOutputW: 22.5,
      multiPortOutput: "5V/3A 22.5W max",
      dimensionsMm: "128 x 73 x 32",
      inputPorts: ["Integrated USB-C cable", "USB-C"],
      outputPorts: ["Integrated USB-C cable", "USB-C", "USB-A"],
      inputParameters: [
        "Integrated USB-C cable: 5V/3A, 9V/2.5A",
        "USB-C: 5V/3A, 9V/2.5A",
      ],
      outputParameters: [
        "Integrated USB-C cable: 5V/3A, 9V/2.23A, 10V/2.25A, 12V/1.67A",
        "USB-C: 5V/3A, 9V/2.23A, 10V/2.25A, 12V/1.67A",
        "USB-A: 5V/3A, 9V/2.23A, 10V/2.25A, 12V/1.67A",
      ],
      packageContents: ["Power bank", "User manual", "Warranty card"],
      listPosition: 7,
    },
  },
  {
    categorySlug: "power-banks",
    manufacturer: "Xiaomi",
    model: "212W HyperCharge Power Bank 24500",
    slug: "xiaomi-212w-hypercharge-power-bank-24500",
    summary:
      "High-output USB-C/USB-A power bank with 212 W max multi-port output and up to 140 W single-port USB-C output.",
    summaryUk:
      "High-output USB-C/USB-A power bank with 212 W max multi-port output and up to 140 W single-port USB-C output.",
    imagePath:
      "https://i02.appmifile.com/473_operatorx_operatorx_opx/26/02/2025/d1539e9f06cf8bb36a91e1cc61c888bc.png",
    priceCents: null,
    productCode: "P03MI",
    nominalVoltageV: 5,
    capacityWh: 89,
    continuousPowerW: 212,
    peakPowerW: 212,
    maxChargeCurrentA: 6,
    chemistry: "Lithium-ion",
    sourceLabel: "Xiaomi official specs",
    sourceLabelUk: "Xiaomi official specs",
    sourceUrl:
      "https://www.mi.com/global/product/xiaomi-212w-hypercharge-power-bank-24500/specs/",
    specifications: {
      ratedCapacityMah: 14000,
      ratedCapacityAt: "5V/6A",
      ratedEnergyWh: 89,
      typicalCapacityMah: 24500,
      batteryVoltageV: 3.63,
      maxInputW: 100,
      maxOutputW: 212,
      singlePortMaxOutputW: 140,
      dimensionsMm: "55.4 x 55.4 x 160",
      inputPorts: ["USB-C"],
      outputPorts: ["USB-C", "USB-A"],
      inputParameters: [
        "USB-C C1: 5V/3A, 9V/3A, 12V/3A, 15V/3A, 20V/3.25A, 20V/5A",
        "USB-C C2: 5V/3A, 9V/3A, 12V/3A, 15V/3A, 20V/2.25A",
      ],
      outputParameters: [
        "USB-C C1: up to 28V/5A, 140W max",
        "USB-C C2: up to 20V/2.25A, 45W max",
        "USB-A: up to 20V/6A, 120W max",
      ],
      multiPortOutput:
        "C1 + C2 + A: up to 65W + 27W + 120W, or 120W + 27W + 2.5W depending on cable",
      packageContents: [
        "Power bank",
        "Charging cable",
        "User manual",
        "Warranty card",
      ],
      listPosition: 8,
    },
  },
  {
    categorySlug: "power-banks",
    manufacturer: "Xiaomi",
    model: "212W HyperCharge Power Bank 25000",
    slug: "xiaomi-212w-hypercharge-power-bank-25000",
    summary:
      "25,000 mAh-class HyperCharge power bank with 212 W max output, 89 Wh rated energy, and 90.8 Wh typical energy.",
    summaryUk:
      "25,000 mAh-class HyperCharge power bank with 212 W max output, 89 Wh rated energy, and 90.8 Wh typical energy.",
    imagePath:
      "https://i02.appmifile.com/213_operatorx_operatorx_opx/26/02/2025/a0d26c9bb8a234d6b3cde4aced24c1db.png",
    priceCents: null,
    productCode: "P03MI",
    nominalVoltageV: 5,
    capacityWh: 89,
    continuousPowerW: 212,
    peakPowerW: 212,
    maxChargeCurrentA: 6,
    chemistry: "Lithium-ion",
    sourceLabel: "Xiaomi official specs",
    sourceLabelUk: "Xiaomi official specs",
    sourceUrl:
      "https://www.mi.com/global/product/xiaomi-212w-hypercharge-power-bank-25000/specs/",
    specifications: {
      ratedCapacityMah: 14000,
      ratedCapacityAt: "5V/6A",
      ratedEnergyWh: 89,
      typicalEnergyWh: 90.8,
      typicalCapacityMah: 25000,
      batteryVoltageV: 3.63,
      maxInputW: 100,
      maxOutputW: 212,
      singlePortMaxOutputW: 140,
      dimensionsMm: "55.4 x 55.4 x 160",
      inputPorts: ["USB-C"],
      outputPorts: ["USB-C", "USB-A"],
      inputParameters: [
        "USB-C C1: 5V/3A, 9V/3A, 12V/3A, 15V/3A, 20V/3.25A, 20V/5A",
        "USB-C C2: 5V/3A, 9V/3A, 12V/3A, 15V/3A, 20V/2.25A",
      ],
      outputParameters: [
        "USB-C C1: up to 28V/5A, 140W max",
        "USB-C C2: up to 20V/2.25A, 45W max",
        "USB-A: up to 20V/6A, 120W max",
      ],
      multiPortOutput:
        "C1 + C2 + A: up to 65W + 27W + 120W, or 120W + 27W + 2.5W depending on cable",
      packageContents: ["Power bank", "Charging cable", "User manual"],
      listPosition: 9,
    },
  },
  {
    categorySlug: "power-banks",
    manufacturer: "Xiaomi",
    model: "165W Power Bank 10000 (Integrated Cable)",
    slug: "xiaomi-165w-power-bank-10000-integrated-cable",
    summary:
      "Compact dual USB-C power bank with integrated cable, 165 W max dual-port output, and up to 90 W self-charging.",
    summaryUk:
      "Compact dual USB-C power bank with integrated cable, 165 W max dual-port output, and up to 90 W self-charging.",
    imagePath:
      "https://i02.appmifile.com/278_operatorx_operatorx_opx/10/01/2025/ea9ce14d10f12f60b9ee6f472bd84ed9.png",
    priceCents: null,
    productCode: "PB1165MI",
    nominalVoltageV: 5,
    capacityWh: 36,
    continuousPowerW: 165,
    peakPowerW: 165,
    maxChargeCurrentA: 8,
    chemistry: "Lithium-ion",
    sourceLabel: "Xiaomi official specs",
    sourceLabelUk: "Xiaomi official specs",
    sourceUrl:
      "https://www.mi.com/global/product/xiaomi-165w-power-bank-10000-integrated-cable/specs/",
    specifications: {
      rawProductModel: "PB1165M|",
      ratedCapacityMah: 5500,
      ratedCapacityAt: "5V/4A",
      ratedEnergyWh: 36,
      batteryCells: "Four 2500mAh batteries",
      typicalCapacityMah: 10000,
      maxInputW: 90,
      maxOutputW: 165,
      dualPortOutput: "120W integrated USB-C cable + 45W USB-C",
      dimensionsMm: "143 x 48 x 36",
      inputPorts: ["Integrated USB-C cable", "USB-C"],
      outputPorts: ["Integrated USB-C cable", "USB-C"],
      inputParameters: [
        "Integrated USB-C cable: 5V/3A, 9V/3A, 12V/3A, 15V/3A, 20V/4.5A",
        "USB-C: 5V/3A, 9V/3A, 12V/3A, 15V/3A, 20V/2.25A",
      ],
      outputParameters: [
        "Dual-port: 5V/4A, 9V/6A, 12V/6A, 15V/6A, 20V/8.25A",
        "Integrated USB-C cable: up to 20V/6A",
        "USB-C: up to 20V/2.25A",
      ],
      packageContents: [
        "Xiaomi 165W Power Bank 10000 (Integrated Cable)",
        "User manual",
      ],
      listPosition: 10,
    },
  },
  {
    categorySlug: "power-banks",
    manufacturer: "Xiaomi",
    model: "33W Power Bank 10000 (Integrated Cable)",
    slug: "xiaomi-33w-power-bank-10000-integrated-cable",
    summary:
      "Compact 10,000 mAh-class power bank with integrated USB-C cable, 33 W max output, and two-device charging.",
    summaryUk:
      "Compact 10,000 mAh-class power bank with integrated USB-C cable, 33 W max output, and two-device charging.",
    imagePath:
      "https://i02.appmifile.com/244_operatorx_operatorx_opx/10/01/2025/f3d54398c5f2c7a1e4e3140ab0154b73.png",
    priceCents: null,
    productCode: "PB1033MI",
    nominalVoltageV: 5,
    capacityWh: 36,
    continuousPowerW: 33,
    peakPowerW: 33,
    maxChargeCurrentA: 3,
    chemistry: "Lithium-ion",
    weightGrams: 210,
    sourceLabel: "Xiaomi official specs",
    sourceLabelUk: "Xiaomi official specs",
    sourceUrl:
      "https://www.mi.com/global/product/xiaomi-33w-power-bank-10000-integrated-cable/specs/",
    specifications: {
      ratedCapacityMah: 5500,
      ratedCapacityAt: "5V/3A",
      ratedEnergyWh: 36,
      typicalCapacityMah: 10000,
      maxInputW: 30,
      maxOutputW: 33,
      multiPortOutput: "5V/3A 15W max",
      dimensionsMm: "105.2 x 65.2 x 26.9",
      inputPorts: ["Integrated USB-C cable", "USB-C"],
      outputPorts: ["Integrated USB-C cable", "USB-C"],
      inputParameters: [
        "Integrated USB-C cable: 5V/3A, 9V/3A, 12V/2.5A",
        "USB-C: 5V/3A, 9V/3A, 12V/2.5A",
      ],
      outputParameters: [
        "Integrated USB-C cable: 5V/3A, 9V/3A, 11V/3A, 12V/2.5A, 15V/2A, 33W max",
        "USB-C: 5V/3A, 9V/3A, 11V/3A, 12V/2.5A, 15V/2A, 33W max",
      ],
      features: [
        "Built-in USB-C cable",
        "Two-way fast charging",
        "Charge two devices simultaneously",
      ],
      packageContents: [
        "Xiaomi 33W Power Bank 10000 (Integrated Cable)",
        "User manual",
        "Warranty card",
      ],
      listPosition: 11,
    },
  },
  {
    categorySlug: "power-banks",
    manufacturer: "Xiaomi",
    model: "Magnetic Power Bank 5000",
    slug: "xiaomi-magnetic-power-bank-5000",
    summary:
      "Magnetic 5,000 mAh-class power bank with USB-C input/output and wireless magnetic charging for phones.",
    summaryUk:
      "Magnetic 5,000 mAh-class power bank with USB-C input/output and wireless magnetic charging for phones.",
    imagePath:
      "https://i02.appmifile.com/312_operatorx_operatorx_opx/20/11/2024/54b0f17b3578347ebe95b38db34fb111.png",
    priceCents: null,
    productCode: "WPB0502MI",
    nominalVoltageV: 5,
    capacityWh: 18,
    continuousPowerW: 18,
    peakPowerW: 18,
    maxChargeCurrentA: 3,
    chemistry: "Lithium-ion",
    weightGrams: 139,
    communicationProtocols: "Magnetic wireless charging",
    sourceLabel: "Xiaomi official specs",
    sourceLabelUk: "Xiaomi official specs",
    sourceUrl:
      "https://www.mi.com/global/product/xiaomi-magnetic-power-bank-5000/specs/",
    specifications: {
      ratedCapacityMah: 2800,
      ratedCapacityAt: "5V/2.4A",
      ratedEnergyWh: 18.5,
      typicalCapacityMah: 5000,
      batteryVoltageV: 3.7,
      maxInputW: 18,
      maxOutputW: 18,
      wirelessOutputW: 10,
      dimensionsMm: "103.7 x 68.3 x 12",
      inputPorts: ["USB-C"],
      outputPorts: ["USB-C", "Wireless magnetic charging"],
      inputParameters: ["USB-C: 5V/3A, 9V/2A"],
      outputParameters: ["USB-C: 5V/2.4A, 9V/2A, 12V/1.5A"],
      features: [
        "Magnetic wireless charging",
        "USB-C wired charging",
        "Compact 5000mAh-class pack",
      ],
      packageContents: [
        "Xiaomi Magnetic Power Bank 5000",
        "USB-C cable",
        "User manual",
      ],
      listPosition: 12,
    },
  },
  {
    categorySlug: "power-banks",
    manufacturer: "Xiaomi",
    model: "Ultra Slim Power Bank 5000mAh",
    slug: "xiaomi-ultra-slim-power-bank-5000mah",
    summary:
      "Ultra-slim 5,000 mAh-class power bank with USB-C input/output, 20 W max output, and 10 mm-class body.",
    summaryUk:
      "Ultra-slim 5,000 mAh-class power bank with USB-C input/output, 20 W max output, and 10 mm-class body.",
    imagePath:
      "https://i02.appmifile.com/758_operatorx_operatorx_opx/15/11/2024/deb170b6ea40d2f3eedbbac31eafab64.png",
    priceCents: null,
    productCode: "PB0520MI",
    nominalVoltageV: 5,
    capacityWh: 19,
    continuousPowerW: 20,
    peakPowerW: 20,
    maxChargeCurrentA: 3,
    chemistry: "Lithium-ion",
    weightGrams: 93,
    sourceLabel: "Xiaomi official specs",
    sourceLabelUk: "Xiaomi official specs",
    sourceUrl:
      "https://www.mi.com/global/product/xiaomi-ultra-slim-power-bank-5000mah/specs/",
    specifications: {
      ratedCapacityMah: 2700,
      ratedCapacityAt: "5V/2.4A",
      ratedEnergyWh: 19.25,
      typicalCapacityMah: 5000,
      batteryVoltageV: 3.85,
      maxInputW: 18,
      maxOutputW: 20,
      dimensionsMm: "113 x 53 x 10",
      inputPorts: ["USB-C"],
      outputPorts: ["USB-C"],
      inputParameters: ["USB-C: 5V/3A, 9V/2A"],
      outputParameters: ["USB-C: 5V/2.4A, 9V/2.22A, 12V/1.67A"],
      features: [
        "Ultra-slim body",
        "USB-C two-way fast charging",
        "Pocket-friendly form factor",
      ],
      packageContents: [
        "Xiaomi Ultra Slim Power Bank 5000mAh",
        "USB-C cable",
        "User manual",
      ],
      listPosition: 13,
    },
  },
  {
    categorySlug: "power-banks",
    manufacturer: "Xiaomi",
    model: "Power Bank 10000mAh 22.5W Lite",
    slug: "xiaomi-power-bank-10000mah-22w-lite",
    summary:
      "Lightweight 10,000 mAh-class power bank with 22.5 W max output, dual USB-A output, and USB-C input.",
    summaryUk:
      "Lightweight 10,000 mAh-class power bank with 22.5 W max output, dual USB-A output, and USB-C input.",
    imagePath:
      "https://i02.appmifile.com/893_operatorx_operatorx_opx/15/10/2024/b5689c87df54d26aacf0b5df488ead2b.png",
    priceCents: null,
    productCode: "PB100LZM",
    nominalVoltageV: 5,
    capacityWh: 37,
    continuousPowerW: 23,
    peakPowerW: 23,
    maxChargeCurrentA: 3,
    chemistry: "Lithium-ion polymer",
    weightGrams: 227,
    sourceLabel: "Xiaomi official specs",
    sourceLabelUk: "Xiaomi official specs",
    sourceUrl:
      "https://www.mi.com/global/product/xiaomi-power-bank-10000mah-22w-lite/specs/",
    specifications: {
      ratedCapacityMah: 5500,
      ratedCapacityAt: "5.1V/2.6A",
      ratedEnergyWh: 37,
      typicalCapacityMah: 10000,
      batteryVoltageV: 3.7,
      maxInputW: 22.5,
      maxOutputW: 22.5,
      dimensionsMm: "148.4 x 73 x 15",
      inputPorts: ["USB-C", "Micro-USB"],
      outputPorts: ["USB-A", "USB-A"],
      inputParameters: [
        "USB-C: 5V/3A, 9V/2.5A",
        "Micro-USB: 5V/2A, 9V/2A, 12V/1.5A",
      ],
      outputParameters: [
        "Single USB-A: 5.1V/2.4A, 9V/2.5A, 12V/1.85A",
        "Dual USB-A: 5.1V/2.6A",
      ],
      features: [
        "22.5W max power",
        "Multiple device compatibility",
        "Dual USB-A output",
      ],
      packageContents: [
        "Power bank",
        "USB-C cable",
        "User manual",
        "Warranty card",
      ],
      listPosition: 14,
    },
  },
  {
    categorySlug: "power-banks",
    manufacturer: "Xiaomi",
    model: "33W Power Bank 20000mAh (Integrated Cable)",
    slug: "xiaomi-33w-power-bank-20000mah-integrated-cable",
    summary:
      "20,000 mAh-class power bank with integrated USB-C cable, 33 W max output, USB-C/USB-A ports, and 30 W input.",
    summaryUk:
      "20,000 mAh-class power bank with integrated USB-C cable, 33 W max output, USB-C/USB-A ports, and 30 W input.",
    imagePath:
      "https://i02.appmifile.com/79_operatorx_operatorx_opx/13/04/2025/0d012e501987fffd60b485f91a7f91d7.png",
    priceCents: null,
    productCode: "PB2033MI",
    nominalVoltageV: 5,
    capacityWh: 74,
    continuousPowerW: 33,
    peakPowerW: 33,
    maxChargeCurrentA: 3,
    chemistry: "Lithium-ion",
    sourceLabel: "Xiaomi official specs",
    sourceLabelUk: "Xiaomi official specs",
    sourceUrl:
      "https://www.mi.com/global/product/xiaomi-33w-power-bank-20000mah-integrated-cable/specs/",
    specifications: {
      ratedCapacityMah: 12000,
      ratedCapacityAt: "5V/3A",
      ratedEnergyWh: 74,
      typicalCapacityMah: 20000,
      maxInputW: 30,
      maxOutputW: 33,
      multiPortOutput: "5V/3A 15W max",
      dimensionsMm: "127 x 70.5 x 30.5",
      inputPorts: ["Integrated USB-C cable", "USB-C"],
      outputPorts: ["Integrated USB-C cable", "USB-C", "USB-A"],
      inputParameters: [
        "Integrated USB-C cable: 5V/3A, 9V/3A, 12V/2.5A",
        "USB-C: 5V/3A, 9V/3A, 12V/2.5A",
      ],
      outputParameters: [
        "Integrated USB-C cable: up to 33W max",
        "USB-C: up to 33W max",
        "USB-A: up to 22.5W max",
      ],
      features: [
        "Integrated USB-C cable",
        "Compatible with multiple devices",
        "Ultra-large battery capacity",
      ],
      packageContents: [
        "Xiaomi 33W Power Bank 20000mAh (Integrated Cable)",
        "User manual",
      ],
      listPosition: 15,
    },
  },
  {
    categorySlug: "power-banks",
    manufacturer: "Xiaomi",
    model: "18W Power Bank 30000mAh",
    slug: "xiaomi-18w-power-bank-30000mah",
    summary:
      "High-capacity 30,000 mAh-class power bank with 18 W fast charging, USB-C/Micro-USB input, and dual USB-A output.",
    summaryUk:
      "High-capacity 30,000 mAh-class power bank with 18 W fast charging, USB-C/Micro-USB input, and dual USB-A output.",
    imagePath:
      "https://i02.appmifile.com/883_operatorx_operatorx_opx/30/07/2024/8d78ecb0ee81a0b009c98463492a0407.jpg",
    priceCents: null,
    productCode: "PB3018ZM",
    nominalVoltageV: 5,
    capacityWh: 111,
    continuousPowerW: 18,
    peakPowerW: 18,
    maxChargeCurrentA: 3,
    chemistry: "Lithium-ion polymer",
    weightGrams: 657,
    sourceLabel: "Xiaomi official specs",
    sourceLabelUk: "Xiaomi official specs",
    sourceUrl:
      "https://www.mi.com/global/product/xiaomi-18w-power-bank-30000mah/specs/",
    specifications: {
      ratedCapacityMah: 18000,
      ratedCapacityAt: "5.1V/3.6A",
      ratedEnergyWh: 111,
      typicalCapacityMah: 30000,
      batteryVoltageV: 3.7,
      maxInputW: 24,
      maxOutputW: 18,
      dimensionsMm: "154.5 x 72.3 x 38.9",
      inputPorts: ["USB-C", "Micro-USB"],
      outputPorts: ["USB-A", "USB-A"],
      inputParameters: ["USB-C: 5V/3A, 9V/2.6A", "Micro-USB: 5V/2A, 9V/2A"],
      outputParameters: [
        "Single USB-A: 5.1V/2.4A, 9V/2A, 12V/1.5A",
        "Dual USB-A: 5.1V/3.6A",
      ],
      features: [
        "High-capacity charging",
        "High-quality battery cell",
        "Smart fast charging",
      ],
      packageContents: ["Power bank", "USB-C cable", "User manual"],
      listPosition: 16,
    },
  },
  {
    categorySlug: "power-banks",
    manufacturer: "Xiaomi",
    model: "Power Bank 10000mAh (Integrated Cable)",
    slug: "xiaomi-power-bank-10000mah-integrated-cable",
    summary:
      "10,000 mAh-class power bank with integrated USB-C cable, USB-C and USB-A outputs, and 22.5 W max output.",
    summaryUk:
      "10,000 mAh-class power bank with integrated USB-C cable, USB-C and USB-A outputs, and 22.5 W max output.",
    imagePath:
      "https://i02.appmifile.com/670_operatorx_operatorx_opx/02/06/2026/04a07ae36ee548daea58c0bd511e9939.png",
    priceCents: null,
    productCode: "PB1022MI",
    nominalVoltageV: 5,
    capacityWh: 37,
    continuousPowerW: 23,
    peakPowerW: 23,
    maxChargeCurrentA: 3,
    chemistry: "Lithium-ion",
    weightGrams: 250,
    sourceLabel: "Xiaomi official specs",
    sourceLabelUk: "Xiaomi official specs",
    sourceUrl:
      "https://www.mi.com/global/product/xiaomi-power-bank-10000mah-integrated-cable/specs/",
    specifications: {
      ratedCapacityMah: 5500,
      ratedCapacityAt: "5V/3A",
      ratedEnergyWh: 37,
      typicalCapacityMah: 10000,
      maxInputW: 22.5,
      maxOutputW: 22.5,
      multiPortOutput: "5V/3A 15W max",
      dimensionsMm: "105.2 x 65.2 x 26.9",
      inputPorts: ["Integrated USB-C cable", "USB-C"],
      outputPorts: ["Integrated USB-C cable", "USB-C", "USB-A"],
      inputParameters: [
        "Integrated USB-C cable: 5V/3A, 9V/2.5A",
        "USB-C: 5V/3A, 9V/2.5A",
      ],
      outputParameters: [
        "Integrated USB-C cable: 5V/3A, 9V/2.23A, 10V/2.25A, 12V/1.67A",
        "USB-C: 5V/3A, 9V/2.23A, 10V/2.25A, 12V/1.67A",
        "USB-A: 5V/3A, 9V/2.23A, 10V/2.25A, 12V/1.67A",
      ],
      features: [
        "Integrated power cable",
        "Compatible with multiple devices",
        "22.5W max power",
      ],
      packageContents: ["Power bank", "User manual", "Warranty card"],
      listPosition: 17,
    },
  },
  {
    categorySlug: "power-banks",
    manufacturer: "Xiaomi",
    model: "Magnetic Power Bank 6000mAh",
    slug: "xiaomi-magnetic-power-bank-6000mah",
    summary:
      "Qi2 magnetic 6,000 mAh-class power bank with 15 W wireless charging and USB-C wired input/output.",
    summaryUk:
      "Qi2 magnetic 6,000 mAh-class power bank with 15 W wireless charging and USB-C wired input/output.",
    imagePath:
      "https://i02.appmifile.com/532_operatorx_operatorx_opx/30/07/2024/c875b3b2dca15897f703b22429440b51.png",
    priceCents: null,
    productCode: "WPB0620MI",
    nominalVoltageV: 5,
    capacityWh: 22,
    continuousPowerW: 20,
    peakPowerW: 20,
    maxChargeCurrentA: 3,
    chemistry: "Lithium-ion",
    weightGrams: 148,
    communicationProtocols: "Qi2 wireless charging",
    sourceLabel: "Xiaomi official specs",
    sourceLabelUk: "Xiaomi official specs",
    sourceUrl:
      "https://www.mi.com/global/product/xiaomi-magnetic-power-bank-6000mah/specs/",
    specifications: {
      ratedCapacityMah: 3600,
      ratedCapacityAt: "5V/2.4A",
      ratedEnergyWh: 22.2,
      typicalCapacityMah: 6000,
      batteryVoltageV: 3.7,
      maxInputW: 18,
      maxOutputW: 20,
      wirelessOutputW: 15,
      dimensionsMm: "103.7 x 68.3 x 15.2",
      inputPorts: ["USB-C"],
      outputPorts: ["USB-C", "Wireless magnetic charging"],
      inputParameters: ["USB-C: 5V/3A, 9V/2A"],
      outputParameters: ["USB-C: 5V/2.4A, 9V/2.22A, 12V/1.67A"],
      features: [
        "15W super-fast wireless charging",
        "Charge and use simultaneously",
        "Suitable for Qi2 Apple devices",
      ],
      packageContents: [
        "Xiaomi Magnetic Power Bank 6000mAh",
        "USB-C cable",
        "User manual",
      ],
      listPosition: 18,
    },
  },
  {
    categorySlug: "power-banks",
    manufacturer: "Xiaomi",
    model: "33W Power Bank 10000mAh Pocket Edition Pro",
    slug: "xiaomi-33w-power-bank-10000mah-pocket-edition-pro",
    summary:
      "Pocket-format 10,000 mAh-class power bank with 33 W max output, USB-C input/output, and dual USB-A output.",
    summaryUk:
      "Pocket-format 10,000 mAh-class power bank with 33 W max output, USB-C input/output, and dual USB-A output.",
    imagePath:
      "https://i01.appmifile.com/v1/MI_18455B3E4DA706226CF7535A58E875F0267/pms_1678936383.60097709.png",
    priceCents: null,
    productCode: "PB1030ZM",
    nominalVoltageV: 5,
    capacityWh: 37,
    continuousPowerW: 33,
    peakPowerW: 33,
    maxChargeCurrentA: 3,
    chemistry: "Lithium-ion polymer",
    weightGrams: 212,
    sourceLabel: "Xiaomi official specs",
    sourceLabelUk: "Xiaomi official specs",
    sourceUrl:
      "https://www.mi.com/global/product/xiaomi-33w-power-bank-10000mah-pocket-edition-pro/specs/",
    specifications: {
      ratedCapacityMah: 5600,
      ratedCapacityAt: "5V/3A",
      ratedEnergyWh: 37,
      typicalCapacityMah: 10000,
      batteryVoltageV: 3.7,
      maxInputW: 22.5,
      maxOutputW: 33,
      dimensionsMm: "105 x 55.8 x 25.5",
      inputPorts: ["USB-C"],
      outputPorts: ["USB-C", "USB-A", "USB-A"],
      inputParameters: ["USB-C: 5V/3A, 9V/2.5A"],
      outputParameters: [
        "USB-C: 5V/3A, 9V/3A, 11V/3A, 12V/2.25A",
        "USB-A: 5V/3A, 9V/2.23A, 12V/1.67A, 10V/2.25A",
      ],
      features: [
        "Pocket Edition Pro form factor",
        "33W max output",
        "USB-C and dual USB-A output",
      ],
      packageContents: [
        "Power bank",
        "USB-C cable",
        "User manual",
        "Warranty card",
      ],
      listPosition: 19,
    },
  },
  {
    categorySlug: "power-banks",
    manufacturer: "Xiaomi",
    model: "10000 mAh Mi Wireless Power Bank",
    slug: "10000mah-mi-wireless-power-bank-essential",
    summary:
      "10,000 mAh-class wireless power bank with USB-C/Micro-USB input, USB-A output, and 10 W wireless charging.",
    summaryUk:
      "10,000 mAh-class wireless power bank with USB-C/Micro-USB input, USB-A output, and 10 W wireless charging.",
    imagePath:
      "https://i01.appmifile.com/v1/MI_18455B3E4DA706226CF7535A58E875F0267/pms_1666872499.8469504.png",
    priceCents: null,
    productCode: "WPB15ZM",
    nominalVoltageV: 5,
    capacityWh: 37,
    continuousPowerW: 18,
    peakPowerW: 18,
    maxChargeCurrentA: 3,
    chemistry: "Lithium-ion polymer",
    weightGrams: 240,
    communicationProtocols: "Qi wireless charging",
    sourceLabel: "Xiaomi official specs",
    sourceLabelUk: "Xiaomi official specs",
    sourceUrl:
      "https://www.mi.com/global/product/10000mah-mi-wireless-power-bank-essential/specs/",
    specifications: {
      ratedCapacityMah: 5800,
      ratedCapacityAt: "5.1V/2.6A",
      ratedEnergyWh: 37,
      typicalCapacityMah: 10000,
      batteryVoltageV: 3.7,
      maxInputW: 18,
      maxOutputW: 18,
      wirelessOutputW: 10,
      dimensionsMm: "147.9 x 70.6 x 16.6",
      inputPorts: ["USB-C", "Micro-USB"],
      outputPorts: ["USB-A", "Wireless charging"],
      inputParameters: [
        "USB-C: 5V/2.4A, 9V/2A, 12V/1.5A",
        "Micro-USB: 5V/2A, 9V/2A, 12V/1.5A",
      ],
      outputParameters: [
        "USB-A: 5.1V/2.4A, 9V/2A, 12V/1.5A",
        "Wireless: 10W max",
      ],
      features: [
        "Wireless charging",
        "USB-C and Micro-USB input",
        "USB-A wired output",
      ],
      packageContents: [
        "Mi Wireless Power Bank Essential",
        "USB-C cable",
        "User manual",
      ],
      listPosition: 20,
    },
  },
  {
    categorySlug: "power-banks",
    manufacturer: "Xiaomi",
    model: "10000mAh Mi Power Bank 3 Ultra Compact",
    slug: "10000mah-mi-power-bank-3-ultra-compact",
    summary:
      "Ultra-compact 10,000 mAh-class power bank with 22.5 W max output, USB-C/Micro-USB input, and three-device charging.",
    summaryUk:
      "Ultra-compact 10,000 mAh-class power bank with 22.5 W max output, USB-C/Micro-USB input, and three-device charging.",
    imagePath:
      "https://i01.appmifile.com/v1/MI_18455B3E4DA706226CF7535A58E875F0267/pms_1666872424.98064819.png",
    priceCents: null,
    productCode: "PB1022ZM",
    nominalVoltageV: 5,
    capacityWh: 37,
    continuousPowerW: 23,
    peakPowerW: 23,
    maxChargeCurrentA: 3,
    chemistry: "Lithium-ion polymer",
    weightGrams: 200,
    sourceLabel: "Xiaomi official specs",
    sourceLabelUk: "Xiaomi official specs",
    sourceUrl:
      "https://www.mi.com/global/product/10000mah-mi-power-bank-3-ultra-compact/specs/",
    specifications: {
      ratedCapacityMah: 5500,
      ratedCapacityAt: "5V/3A",
      ratedEnergyWh: 37,
      typicalCapacityMah: 10000,
      batteryVoltageV: 3.7,
      conversionRate: "74% (5V/3A)",
      maxInputW: 22.5,
      maxOutputW: 22.5,
      dimensionsMm: "90 x 63.9 x 24.4",
      workingTemperatureC: "5 to 35",
      chargingTime: [
        "Approximately 3.5 hours with PD 24W charger or above and C to C cable",
        "Approximately 6 hours with 5V/2A charger and included cable",
      ],
      inputPorts: ["USB-C", "Micro-USB"],
      outputPorts: ["USB-A", "USB-C"],
      inputParameters: ["USB-C: 5V/3A, 9V/2.5A", "Micro-USB: 5V/2A, 9V/2A"],
      outputParameters: [
        "22.5W max",
        "Multiple ports: 5V/3A",
        "USB-A: 5V/2.4A, 9V/2.5A max, 12V/1.85A max",
        "USB-C: 5V/3A, 9V/2.5A max, 12V/1.85A max",
      ],
      features: [
        "Ultra-compact body",
        "Can charge three devices simultaneously",
        "Low-current charging mode",
        "Suitable for air travel under 100 Wh",
      ],
      packageContents: [
        "10000mAh Mi Power Bank 3 Ultra Compact",
        "USB-A to USB-C cable",
        "User manual",
      ],
      listPosition: 21,
    },
  },
  {
    categorySlug: "power-banks",
    manufacturer: "Xiaomi",
    model: "Mi 50W Power Bank 20000mAh",
    slug: "mi-50w-power-bank-20000",
    summary:
      "20,000 mAh-class laptop-capable power bank with 50 W USB-C output, 45 W input, and three-port charging.",
    summaryUk:
      "20,000 mAh-class laptop-capable power bank with 50 W USB-C output, 45 W input, and three-port charging.",
    imagePath:
      "https://i01.appmifile.com/v1/MI_18455B3E4DA706226CF7535A58E875F0267/pms_1666872404.25699306.png",
    priceCents: null,
    productCode: "PB200SZM",
    nominalVoltageV: 5,
    capacityWh: 74,
    continuousPowerW: 50,
    peakPowerW: 50,
    maxChargeCurrentA: 5,
    chemistry: "Lithium-ion polymer",
    sourceLabel: "Xiaomi official specs",
    sourceLabelUk: "Xiaomi official specs",
    sourceUrl:
      "https://www.mi.com/global/product/mi-50w-power-bank-20000/specs/",
    specifications: {
      ratedCapacityMah: 12000,
      ratedCapacityAt: "5V/4A",
      ratedEnergyWh: 74,
      typicalCapacityMah: 20000,
      batteryVoltageV: 3.7,
      maxInputW: 45,
      maxOutputW: 50,
      operatingTemperatureC: "5 to 35",
      chargingTime: [
        "Approximately 11 hours with 5V/2A charger",
        "Approximately 6.5 hours with 18W charger",
        "Approximately 4.5 hours with 45W charger and package cable",
      ],
      inputPorts: ["USB-C"],
      outputPorts: ["USB-A", "USB-A", "USB-C"],
      inputParameters: ["5V/3A, 9V/3A, 12V/3A, 15V/3A, 20V/2.25A"],
      outputParameters: [
        "50W max",
        "USB-A single port: 5V/3A, 9V/2.23A, 12V/1.67A, 10V/2.25A",
        "USB-A two ports: 5V/3A",
        "USB-C: 5V/3A, 9V/3A, 10V/5A, 12V/3A, 15V/3A, 20V/2A",
        "Three ports: 5V/4A, 9V/3A, 10V/5A, 12V/3A, 15V/3A, 20V/2A",
      ],
      features: [
        "Charges laptops over USB-C",
        "Can charge three devices simultaneously",
        "Low-current charging mode",
        "Suitable for air travel under 100 Wh",
      ],
      packageContents: [
        "Mi 50W Power Bank 20000mAh",
        "Charging cable",
        "User manual",
      ],
      listPosition: 22,
    },
  },
  {
    categorySlug: "power-banks",
    manufacturer: "Xiaomi",
    model: "Xiaomi 10W Wireless Power Bank 10000",
    slug: "xiaomi-10w-wireless-power-bank-10000",
    summary:
      "10,000 mAh-class wireless power bank with 10 W wireless output, 22.5 W wired fast charging, and pass-through charging.",
    summaryUk:
      "10,000 mAh-class wireless power bank with 10 W wireless output, 22.5 W wired fast charging, and pass-through charging.",
    imagePath:
      "https://i01.appmifile.com/v1/MI_18455B3E4DA706226CF7535A58E875F0267/pms_1666841240.21987017.png",
    priceCents: null,
    productCode: "WPB15PDZM",
    nominalVoltageV: 5,
    capacityWh: 36,
    continuousPowerW: 23,
    peakPowerW: 23,
    maxChargeCurrentA: 3,
    chemistry: "Lithium-ion polymer",
    weightGrams: 240,
    communicationProtocols: "Qi wireless charging",
    sourceLabel: "Xiaomi official specs",
    sourceLabelUk: "Xiaomi official specs",
    sourceUrl:
      "https://www.mi.com/global/product/xiaomi-10w-wireless-power-bank-10000/specs/",
    specifications: {
      ratedCapacityMah: 5600,
      ratedCapacityAt: "5V/3A",
      ratedEnergyWh: 35.2,
      typicalEnergyWh: 36,
      ratedBatteryMah: 9800,
      typicalCapacityMah: 10000,
      maxInputW: 22.5,
      maxOutputW: 22.5,
      wirelessOutputW: 10,
      inductionDistanceMm: 5,
      dimensionsMm: "147.9 x 70.6 x 16.6",
      operatingTemperatureC: "5 to 35",
      inputPorts: ["USB-C"],
      outputPorts: ["USB-A", "USB-C", "Wireless charging"],
      inputParameters: ["5V/3A, 9V/2.5A"],
      outputParameters: [
        "USB-A: 5V/3A, 9V/2.23A, 12V/1.67A, 10V/2.25A max",
        "USB-C: 5V/3A, 9V/2.23A, 12V/1.67A, 10V/2.25A max",
        "Dual port: 5V/3A",
        "Wireless: 10W max",
      ],
      features: [
        "10W wireless fast charging",
        "22.5W wired fast charging",
        "Pass-through charging",
        "Can charge up to three devices at once",
      ],
      packageContents: [
        "Xiaomi 10W Wireless Power Bank 10000",
        "Charging cable",
        "User manual",
      ],
      listPosition: 23,
    },
  },
  {
    categorySlug: "power-banks",
    manufacturer: "Xiaomi",
    model: "20000 mAh Redmi Fast Charge Power Bank",
    slug: "20000mah-redmi-fast-charge-power-bank",
    summary:
      "20,000 mAh-class Redmi fast-charge power bank with USB-C/Micro-USB input and dual USB-A output.",
    summaryUk:
      "20,000 mAh-class Redmi fast-charge power bank with USB-C/Micro-USB input and dual USB-A output.",
    imagePath:
      "https://i01.appmifile.com/v1/MI_18455B3E4DA706226CF7535A58E875F0267/pms_1666845794.21862206.png",
    priceCents: null,
    productCode: "PB200LZM",
    nominalVoltageV: 5,
    capacityWh: 74,
    continuousPowerW: 18,
    peakPowerW: 18,
    maxChargeCurrentA: 4,
    chemistry: "Lithium-ion polymer",
    sourceLabel: "Xiaomi official specs",
    sourceLabelUk: "Xiaomi official specs",
    sourceUrl:
      "https://www.mi.com/global/product/20000mah-redmi-fast-charge-power-bank/specs/",
    specifications: {
      ratedCapacityMah: 12000,
      ratedCapacityAt: "5.1V/3.6A",
      ratedEnergyWh: 74,
      typicalCapacityMah: 20000,
      batteryVoltageV: 3.7,
      maxOutputW: 18,
      dimensionsMm: "154 x 73.6 x 27.3",
      inputPorts: ["Micro-USB", "USB-C"],
      outputPorts: ["USB-A", "USB-A"],
      outputParameters: [
        "5V/2.1A, 9V/2.1A, 12V/1.5A",
        "Single-port output: 5.1V/2.4A, 9V/max 2A, 12V/max 1.5A",
        "Dual-port output: 5.1V/3.6A",
      ],
      features: [
        "Dual USB-A output",
        "USB-C and Micro-USB input",
        "20,000 mAh-class capacity",
      ],
      packageContents: [
        "20,000-mAh Redmi Fast Charge Power Bank",
        "Instruction manual",
        "Power cable",
      ],
      listPosition: 24,
    },
  },
  {
    categorySlug: "power-banks",
    manufacturer: "Xiaomi",
    model: "10000mAh Mi 18W Fast Charge Power Bank 3",
    slug: "10000mah-mi-18w-fast-charge-power-bank-3",
    summary:
      "10,000 mAh-class aluminium power bank with 18 W fast charging, dual input, dual USB-A output, and low-current mode.",
    summaryUk:
      "10,000 mAh-class aluminium power bank with 18 W fast charging, dual input, dual USB-A output, and low-current mode.",
    imagePath:
      "https://i01.appmifile.com/webfile/globalimg/products/pc/10000mAh-mi-18w-fast-charge-power-bank-3//index_0061.png",
    priceCents: null,
    nominalVoltageV: 5,
    capacityWh: 37,
    continuousPowerW: 18,
    peakPowerW: 18,
    chemistry: "Lithium-ion polymer",
    sourceLabel: "Xiaomi official product page",
    sourceLabelUk: "Xiaomi official product page",
    sourceUrl:
      "https://www.mi.com/global/10000mAh-mi-18w-fast-charge-power-bank-3/",
    specifications: {
      typicalCapacityMah: 10000,
      ratedEnergyWh: 37,
      maxInputW: 18,
      maxOutputW: 18,
      chargingTime: ["Self-charging can be completed in 4 hours"],
      inputPorts: ["Micro-USB", "USB-C"],
      outputPorts: ["USB-A", "USB-A"],
      outputParameters: [
        "Single USB-A port supports 18W max fast charging",
        "Dual USB-A output can charge two devices at the same time",
      ],
      features: [
        "Aluminium alloy metal cover",
        "Dual port input",
        "Dual USB-A output",
        "Low-current charging mode",
        "Suitable for air travel under 100 Wh",
      ],
      packageContents: ["Power bank", "Micro-USB cable"],
      listPosition: 25,
    },
  },
  {
    categorySlug: "inverters",
    manufacturer: "Victron Energy",
    model: "MultiPlus-II 48/5000",
    slug: "victron-multiplus-ii-48-5000",
    summary: "48 V inverter-charger for off-grid and ESS installations.",
    summaryUk: "Інвертор-зарядний пристрій 48 В для автономних систем і ESS.",
    imagePath: "/catalog/inverter.svg",
    priceCents: 141900,
    nominalVoltageV: 48,
    continuousPowerW: 4000,
    peakPowerW: 9000,
    maxChargeCurrentA: 70,
    communicationProtocols: "VE.Bus, CAN",
    weightGrams: 30000,
    warrantyYears: 5,
    sourceLabel: "Mock datasheet",
    sourceLabelUk: "Тестовий даташит",
  },
  {
    categorySlug: "inverters",
    manufacturer: "Growatt",
    model: "SPF 5000 ES",
    slug: "growatt-spf-5000-es",
    summary: "Hybrid inverter with integrated MPPT for residential backup.",
    summaryUk:
      "Гібридний інвертор з вбудованим MPPT для домашнього резервного живлення.",
    imagePath: "/catalog/inverter.svg",
    priceCents: 89900,
    nominalVoltageV: 48,
    continuousPowerW: 5000,
    peakPowerW: 10000,
    maxPvVoltageV: 450,
    maxChargeCurrentA: 100,
    communicationProtocols: "RS485, CAN",
    weightGrams: 12000,
    warrantyYears: 5,
    sourceLabel: "Mock manual",
    sourceLabelUk: "Тестова інструкція",
  },
  {
    categorySlug: "inverters",
    manufacturer: "Renogy",
    model: "REGO 3000",
    slug: "renogy-rego-3000",
    summary: "Compact pure sine inverter-charger for vans and cabins.",
    summaryUk:
      "Компактний інвертор-зарядний пристрій із чистою синусоїдою для фургонів і будинків.",
    imagePath: "/catalog/inverter.svg",
    priceCents: 64900,
    nominalVoltageV: 24,
    continuousPowerW: 3000,
    peakPowerW: 6000,
    maxChargeCurrentA: 75,
    communicationProtocols: "Bluetooth",
    weightGrams: 9200,
    warrantyYears: 3,
    sourceLabel: "Mock installation guide",
    sourceLabelUk: "Тестовий посібник з монтажу",
  },
  {
    categorySlug: "batteries",
    manufacturer: "Pylontech",
    model: "US5000",
    slug: "pylontech-us5000",
    summary: "Rack-mounted LFP battery module for expandable 48 V storage.",
    summaryUk:
      "Стійковий LFP акумуляторний модуль для розширюваного сховища 48 В.",
    imagePath: "/catalog/battery.svg",
    priceCents: 154900,
    nominalVoltageV: 48,
    capacityWh: 4800,
    maxChargeCurrentA: 80,
    chemistry: "LiFePO4",
    communicationProtocols: "CAN, RS485",
    weightGrams: 41000,
    warrantyYears: 10,
    lifecycleCycles: 6000,
    sourceLabel: "Mock datasheet",
    sourceLabelUk: "Тестовий даташит",
  },
  {
    categorySlug: "batteries",
    manufacturer: "Renogy",
    model: "Core 12V 200Ah",
    slug: "renogy-core-12v-200ah",
    summary: "Drop-in LFP battery for RVs, boats, and small backup systems.",
    summaryUk:
      "LFP акумулятор для прямої заміни у кемперах, човнах і малих резервних системах.",
    imagePath: "/catalog/battery.svg",
    priceCents: 79900,
    nominalVoltageV: 12,
    capacityWh: 2560,
    maxChargeCurrentA: 100,
    chemistry: "LiFePO4",
    communicationProtocols: "Bluetooth",
    weightGrams: 26300,
    warrantyYears: 5,
    lifecycleCycles: 4000,
    sourceLabel: "Mock product sheet",
    sourceLabelUk: "Тестова специфікація продукту",
  },
  {
    categorySlug: "batteries",
    manufacturer: "Victron Energy",
    model: "SuperPack 25.6V 100Ah",
    slug: "victron-superpack-25v-100ah",
    summary: "Protected LFP module for compact low-voltage systems.",
    summaryUk: "Захищений LFP модуль для компактних низьковольтних систем.",
    imagePath: "/catalog/battery.svg",
    priceCents: 132500,
    nominalVoltageV: 24,
    capacityWh: 2560,
    maxChargeCurrentA: 100,
    chemistry: "LiFePO4",
    communicationProtocols: "BMS port",
    weightGrams: 28000,
    warrantyYears: 3,
    lifecycleCycles: 2500,
    sourceLabel: "Mock manual",
    sourceLabelUk: "Тестова інструкція",
  },
  {
    categorySlug: "power-stations",
    manufacturer: "EcoFlow",
    model: "Delta 2 Max",
    slug: "ecoflow-delta-2-max",
    summary: "Expandable portable power station with fast AC charging.",
    summaryUk:
      "Розширювана портативна електростанція зі швидкою зарядкою від мережі.",
    imagePath: "/catalog/power-station.svg",
    priceCents: 129900,
    nominalVoltageV: 51,
    capacityWh: 2048,
    continuousPowerW: 2400,
    peakPowerW: 4800,
    maxPvVoltageV: 60,
    chemistry: "LiFePO4",
    weightGrams: 23000,
    warrantyYears: 5,
    lifecycleCycles: 3000,
    sourceLabel: "Mock datasheet",
    sourceLabelUk: "Тестовий даташит",
  },
  {
    categorySlug: "power-stations",
    manufacturer: "Bluetti",
    model: "AC200L",
    slug: "bluetti-ac200l",
    summary: "High-capacity portable station for home backup and field power.",
    summaryUk:
      "Портативна станція великої ємності для домашнього резерву та польового живлення.",
    imagePath: "/catalog/power-station.svg",
    priceCents: 159900,
    nominalVoltageV: 51,
    capacityWh: 2048,
    continuousPowerW: 2400,
    peakPowerW: 3600,
    maxPvVoltageV: 145,
    chemistry: "LiFePO4",
    weightGrams: 28000,
    warrantyYears: 5,
    lifecycleCycles: 3000,
    sourceLabel: "Mock product page",
    sourceLabelUk: "Тестова сторінка продукту",
  },
  {
    categorySlug: "power-stations",
    manufacturer: "Anker",
    model: "Solix F2000",
    slug: "anker-solix-f2000",
    summary: "Rolling power station with UPS support and app monitoring.",
    summaryUk:
      "Пересувна електростанція з підтримкою UPS і моніторингом через застосунок.",
    imagePath: "/catalog/power-station.svg",
    priceCents: 139900,
    nominalVoltageV: 51,
    capacityWh: 2048,
    continuousPowerW: 2400,
    peakPowerW: 3200,
    maxPvVoltageV: 60,
    chemistry: "LiFePO4",
    weightGrams: 30500,
    warrantyYears: 5,
    lifecycleCycles: 3000,
    sourceLabel: "Mock quick-start guide",
    sourceLabelUk: "Тестовий короткий посібник",
  },
];

const victronInverterRows: SeedEquipment[] = [
  {
    categorySlug: "inverters",
    manufacturer: "Victron Energy",
    model: "MultiPlus 500VA - 1600VA",
    slug: "victron-multiplus-500va-1600va",
    summary:
      "Compact true sine wave inverter-charger range with adaptive charging, a high-speed AC transfer switch, UPS switchover, and GX/VRM monitoring support.",
    summaryUk:
      "Compact true sine wave inverter-charger range with adaptive charging, a high-speed AC transfer switch, UPS switchover, and GX/VRM monitoring support.",
    imagePath:
      "https://media.vladyka.dev/inverter/victron/Multiplus_500-1600.png",
    priceCents: null,
    continuousPowerW: 1600,
    communicationProtocols: "VE.Bus, GX, VRM",
    warrantyYears: 5,
    sourceLabel: "Victron Energy product page",
    sourceLabelUk: "Victron Energy product page",
    sourceUrl: "https://www.victronenergy.com/inverters-chargers/multi-500-va",
    specifications: {
      sourceCategoryUrl: "https://www.victronenergy.com/inverters-chargers",
      collectionListPosition: 1,
      productFamily: "MultiPlus",
      productType: "Inverter/charger",
      models: ["500VA", "800VA", "1200VA", "1600VA"],
      outputRangeVa: [500, 800, 1200, 1600],
      nominalVoltagesV: [12, 24, 48],
      inverterWaveform: "True sine wave",
      transferSwitch: "High-speed AC transfer switch",
      upsTransferTimeMs: "<20",
      batteryCharging: "Adaptive charge technology",
      acInputs: 1,
      acOutputs: 2,
      monitoring: ["GX device", "VRM app", "VRM portal"],
      features: [
        "Uninterrupted AC power UPS function",
        "Remote monitoring and control with a GX device",
        "Compact enclosure",
      ],
      datasheets: ["MultiPlus 500VA - 2000VA PDF"],
    },
  },
  {
    categorySlug: "inverters",
    manufacturer: "Victron Energy",
    model: "MultiPlus",
    slug: "victron-multiplus",
    summary:
      "Combined inverter and charger family with true sine wave output, adaptive charging, PowerAssist, parallel operation, and multiple system integration options.",
    summaryUk:
      "Combined inverter and charger family with true sine wave output, adaptive charging, PowerAssist, parallel operation, and multiple system integration options.",
    imagePath: "https://media.vladyka.dev/inverter/victron/MultiPlus_20k.png",
    priceCents: null,
    continuousPowerW: 20000,
    communicationProtocols: "VE.Bus, GX, VRM",
    warrantyYears: 5,
    sourceLabel: "Victron Energy product page",
    sourceLabelUk: "Victron Energy product page",
    sourceUrl:
      "https://www.victronenergy.com/inverters-chargers/multiplus-12v-24v-48v-800va-3kva",
    specifications: {
      sourceCategoryUrl: "https://www.victronenergy.com/inverters-chargers",
      collectionListPosition: 2,
      productFamily: "MultiPlus",
      productType: "Inverter/charger",
      models: [
        "800VA",
        "1200VA",
        "1600VA",
        "2000VA",
        "3000VA",
        "5000VA",
        "20kW",
      ],
      outputRangeVa: [800, 1200, 1600, 2000, 3000, 5000],
      outputRangeW: [20000],
      nominalVoltagesV: [12, 24, 48],
      inverterWaveform: "True sine wave",
      acInputs: 1,
      acOutputs: 2,
      parallelUnitsMax: 4,
      supportsThreePhase: true,
      supportsSplitPhase: true,
      monitoring: ["GX device", "VRM app", "VRM portal"],
      features: [
        "Hybrid PowerAssist technology",
        "Uninterrupted AC power UPS function",
        "Parallel operation for higher power output",
        "Three phase or split phase operation",
      ],
      datasheets: [
        "MultiPlus 48V 20kW PDF",
        "MultiPlus Inverter/Charger 800VA - 5kVA PDF",
      ],
    },
  },
  {
    categorySlug: "inverters",
    manufacturer: "Victron Energy",
    model: "MultiPlus 2000VA",
    slug: "victron-multiplus-2000va",
    summary:
      "2000VA MultiPlus inverter-charger with PowerAssist, adaptive charging, UPS switchover, and support for parallel, three-phase, or split-phase operation.",
    summaryUk:
      "2000VA MultiPlus inverter-charger with PowerAssist, adaptive charging, UPS switchover, and support for parallel, three-phase, or split-phase operation.",
    imagePath:
      "https://media.vladyka.dev/inverter/victron/MultiPlus_12_2000VA_80_230V_(front).png",
    priceCents: null,
    continuousPowerW: 2000,
    communicationProtocols: "VE.Bus, GX, VRM",
    warrantyYears: 5,
    sourceLabel: "Victron Energy product page",
    sourceLabelUk: "Victron Energy product page",
    sourceUrl:
      "https://www.victronenergy.com/inverters-chargers/multiplus-2000-va",
    specifications: {
      sourceCategoryUrl: "https://www.victronenergy.com/inverters-chargers",
      collectionListPosition: 3,
      productFamily: "MultiPlus",
      productType: "Inverter/charger",
      models: ["2000VA"],
      outputRangeVa: [2000],
      nominalVoltagesV: [12, 24, 48],
      inverterWaveform: "True sine wave",
      parallelUnitsMax: 4,
      supportsThreePhase: true,
      supportsSplitPhase: true,
      upsTransferTimeMs: "<20",
      monitoring: ["GX device", "VRM app", "VRM portal"],
      features: [
        "PowerAssist for limited AC sources",
        "Uninterrupted AC power UPS function",
        "Parallel operation for higher power output",
        "Remote monitoring and control",
      ],
      datasheets: ["MultiPlus 2000VA 120V PDF", "MultiPlus 500VA - 2000VA PDF"],
    },
  },
  {
    categorySlug: "inverters",
    manufacturer: "Victron Energy",
    model: "MultiPlus-II",
    slug: "victron-multiplus-ii",
    summary:
      "Multifunctional inverter-charger family for marine, vehicle, off-grid, and ESS systems with two AC outputs, PowerControl, PowerAssist, and scalable parallel or three-phase configurations.",
    summaryUk:
      "Multifunctional inverter-charger family for marine, vehicle, off-grid, and ESS systems with two AC outputs, PowerControl, PowerAssist, and scalable parallel or three-phase configurations.",
    imagePath: "https://media.vladyka.dev/inverter/victron/MultiPlus-II_nw.png",
    priceCents: null,
    continuousPowerW: 15000,
    communicationProtocols: "VE.Bus, GX, VRM",
    warrantyYears: 5,
    sourceLabel: "Victron Energy product page",
    sourceLabelUk: "Victron Energy product page",
    sourceUrl: "https://www.victronenergy.com/inverters-chargers/multiplus-ii",
    specifications: {
      sourceCategoryUrl: "https://www.victronenergy.com/inverters-chargers",
      collectionListPosition: 4,
      productFamily: "MultiPlus-II",
      productType: "Inverter/charger",
      formerName: "MultiGrid-II",
      models: [
        "3000VA",
        "4kVA",
        "4k5VA",
        "5000VA",
        "6k5VA",
        "8000VA",
        "10000VA",
        "15000VA",
      ],
      outputRangeVa: [3000, 4000, 4500, 5000, 6500, 8000, 10000, 15000],
      nominalVoltagesV: [12, 24, 48],
      acOutputs: 2,
      supportsEss: true,
      supportsParallel: true,
      supportsThreePhase: true,
      upsTransferTimeMs: "<20",
      batteryCharging: "Smart adaptive charging algorithm",
      monitoring: ["GX device", "VRM app", "VRM portal"],
      features: [
        "PowerControl prevents grid or generator overload",
        "PowerAssist boosts AC power during peak demand",
        "ESS support",
        "Uninterrupted AC power UPS function",
      ],
      datasheets: [
        "MultiPlus-II 120V PDF",
        "MultiPlus-II 3kVA - 15kVA 230V PDF",
        "MultiPlus-II 4k, 4k5 and 6k5 230V PDF",
      ],
    },
  },
  {
    categorySlug: "inverters",
    manufacturer: "Victron Energy",
    model: "MultiPlus-II 2x 120V",
    slug: "victron-multiplus-ii-2x-120v",
    summary:
      "Split-phase MultiPlus-II inverter-charger for 120/240V systems, based on the MultiPlus-II platform with PowerControl, PowerAssist, and GX/VRM monitoring support.",
    summaryUk:
      "Split-phase MultiPlus-II inverter-charger for 120/240V systems, based on the MultiPlus-II platform with PowerControl, PowerAssist, and GX/VRM monitoring support.",
    imagePath:
      "https://media.vladyka.dev/inverter/victron/MultiPlus-II_12_3000_120-50_2x120V_(front)nw.png",
    priceCents: null,
    continuousPowerW: 3000,
    communicationProtocols: "VE.Bus, GX, VRM",
    warrantyYears: 5,
    sourceLabel: "Victron Energy product page",
    sourceLabelUk: "Victron Energy product page",
    sourceUrl:
      "https://www.victronenergy.com/inverters-chargers/multiplus-ii-2x-120v",
    specifications: {
      sourceCategoryUrl: "https://www.victronenergy.com/inverters-chargers",
      collectionListPosition: 5,
      productFamily: "MultiPlus-II",
      productType: "Inverter/charger",
      models: ["3000VA"],
      outputRangeVa: [3000],
      nominalVoltagesV: [12, 24],
      acSystem: "2x 120V split-phase",
      supportsSplitPhase: true,
      monitoring: ["GX device", "VRM app", "VRM portal"],
      features: [
        "Designed for 120/240V split-phase systems",
        "PowerControl and PowerAssist platform features",
        "Remote monitoring and control with a GX device",
      ],
      datasheets: ["MultiPlus-II 2x 120V PDF"],
    },
  },
];

const ecoFlowPowerStationRows: SeedEquipment[] = [
  {
    categorySlug: "power-stations",
    manufacturer: "EcoFlow",
    model: "DELTA 3 Classic (1024Wh)",
    slug: "ecoflow-delta-3-classic-1024wh",
    summary:
      "1,024 Wh LFP portable power station with 1,800 W AC output, 3,600 W surge, 500 W solar input, and 10 ms UPS switching.",
    summaryUk:
      "1,024 Wh LFP portable power station with 1,800 W AC output, 3,600 W surge, 500 W solar input, and 10 ms UPS switching.",
    imagePath:
      "https://media.vladyka.dev/power-station/ecoflow/ecoflow-delta-3-classic-1024wh-portable-power-station-1218691755.webp",
    priceCents: 54900,
    productCode: "EFDELTA3C-EU-CBox-L",
    nominalVoltageV: 230,
    capacityWh: 1024,
    continuousPowerW: 1800,
    peakPowerW: 3600,
    maxPvVoltageV: 60,
    chemistry: "LFP",
    communicationProtocols: "Wi-Fi, Bluetooth, EcoFlow app",
    weightGrams: 12100,
    warrantyYears: 5,
    sourceLabel: "EcoFlow official product page",
    sourceLabelUk: "EcoFlow official product page",
    sourceUrl:
      "https://eu.ecoflow.com/products/delta-3-classic-portable-power-station",
    specifications: {
      collectionListPosition: 1,
      capacityWh: 1024,
      outputVoltageV: 230,
      totalOutputPorts: 5,
      acOutlets: 3,
      maxOutputWithXBoostW: 2400,
      maxInputW: 1400,
      maxSolarInputW: 500,
      acCharging: "1400W, about 60 minutes",
      generatorChargingW: 1400,
      usbPorts: ["USB-A 12W", "USB-C 100W", "USB-C 30W"],
      dcOutput: "No 12V DC output",
      upsTransferMs: 10,
      dimensionsMm: "398 x 200 x 283",
      noise: ["600W < 30dB", "1200W < 40dB"],
      chargeTemperatureC: "0 to 45",
      dischargeTemperatureC: "-10 to 45",
      storageTemperatureC: "-10 to 45",
      operatingAltitudeM: 3000,
      packageContents: ["DELTA 3 Classic"],
      features: [
        "Automotive-grade full-tab LFP cells",
        "OASIS 3.0 smart app control",
        "Storm Guard Mode",
      ],
    },
  },
  {
    categorySlug: "power-stations",
    manufacturer: "EcoFlow",
    model: "DELTA 3 Max Plus (2048Wh)",
    slug: "ecoflow-delta-3-max-plus-2048wh",
    summary:
      "2,048 Wh LFP station with 3,000 W AC output, 6,000 W surge, 1,000 W solar charging, and expandable capacity up to 10 kWh.",
    summaryUk:
      "2,048 Wh LFP station with 3,000 W AC output, 6,000 W surge, 1,000 W solar charging, and expandable capacity up to 10 kWh.",
    imagePath:
      "https://media.vladyka.dev/power-station/ecoflow/ecoflow-delta-3-max-series-portable-power-station-1197150547.webp",
    priceCents: 119900,
    productCode: "EFD3MP-EU-CBOX",
    nominalVoltageV: 230,
    capacityWh: 2048,
    continuousPowerW: 3000,
    peakPowerW: 6000,
    maxPvVoltageV: 60,
    chemistry: "LFP",
    communicationProtocols: "Wi-Fi, Bluetooth, EcoFlow app",
    weightGrams: 22100,
    warrantyYears: 5,
    sourceLabel: "EcoFlow official product page",
    sourceLabelUk: "EcoFlow official product page",
    sourceUrl:
      "https://eu.ecoflow.com/products/delta-3-max-series-portable-power-station",
    specifications: {
      collectionListPosition: 2,
      capacityWh: 2048,
      totalOutputPorts: 10,
      acOutlets: 4,
      maxOutputWithXBoostW: 3900,
      maxInputW: 2300,
      maxSolarInputW: 1000,
      acCharging: "2300W, about 68 minutes",
      generatorChargingW: 2400,
      alternatorChargingW: 1000,
      usbPorts: ["USB-A 18W", "USB-C 140W", "2 x USB-C 45W shared"],
      dcOutput: "378W max; car power output 12.6V/10A; Anderson 12.6V/30A",
      carCharging: "12V/24V, 8A",
      extraBatteryPorts: 1,
      compatibleExtraBatteries: [
        "DELTA 2 Max",
        "DELTA 3 Max Plus",
        "DELTA Pro 3",
        "DELTA 3 Extra Battery",
      ],
      expandableCapacity: "Up to 10kWh",
      upsTransferMs: 10,
      dimensionsMm: "494 x 242 x 305",
      noise: "600W <= 25dB",
      chargeTemperatureC: "0 to 45",
      dischargeTemperatureC: "-10 to 45",
      storageTemperatureC: "-10 to 45",
      operatingAltitudeM: 3000,
      packageContents: ["DELTA 3 Max Plus"],
      features: [
        "Smart Output Priority",
        "X-Fusion support",
        "Full-tab LFP cells",
      ],
    },
  },
  {
    categorySlug: "power-stations",
    manufacturer: "EcoFlow",
    model: "DELTA 2 Max",
    slug: "ecoflow-delta-2-max",
    summary:
      "Expandable 2,048 Wh LFP portable station with 2,400 W AC output, 4,800 W surge, dual 500 W solar inputs, and app control.",
    summaryUk:
      "Expandable 2,048 Wh LFP portable station with 2,400 W AC output, 4,800 W surge, dual 500 W solar inputs, and app control.",
    imagePath:
      "https://media.vladyka.dev/power-station/ecoflow/ecoflow-delta-2-max-portable-power-station-51305159590231.webp",
    priceCents: 99900,
    productCode: "EFDELTA2Max-EU",
    nominalVoltageV: 230,
    capacityWh: 2048,
    continuousPowerW: 2400,
    peakPowerW: 4800,
    maxPvVoltageV: 60,
    chemistry: "LFP",
    communicationProtocols: "Wi-Fi, Bluetooth",
    weightGrams: 23000,
    warrantyYears: 5,
    lifecycleCycles: 3000,
    sourceLabel: "EcoFlow official product page",
    sourceLabelUk: "EcoFlow official product page",
    sourceUrl:
      "https://eu.ecoflow.com/products/delta-2-max-portable-power-station",
    specifications: {
      collectionListPosition: 3,
      capacityWh: 2048,
      expandableCapacity: "2-6kWh",
      extraBattery:
        "Supports up to two DELTA 2 Max Smart Extra Batteries or DELTA Max Smart Extra Batteries",
      acOutput: "4 outlets, 2400W total, 4800W surge",
      maxOutputWithXBoostW: 3100,
      maxInputW: 2300,
      acCharging: "X-Stream fast charge 2300W, 10A",
      solarCharging: "11-60V 15A, single port 500W; dual port 1000W",
      maxSolarInputW: 1000,
      carCharging: "12V/24V battery, 8A",
      outputPorts: [
        "2 x USB-A 12W",
        "2 x USB-A fast charge 18W",
        "2 x USB-C 100W",
        "Car power 126W",
        "2 x DC5521 38W",
      ],
      dimensionsMm: "497 x 242 x 305",
      netWeightKg: 23,
      noise: "As quiet as 30dB",
      packageContents: [
        "DELTA 2 Max",
        "AC charging cable",
        "User manual",
        "Warranty card",
      ],
      features: [
        "AC Always On mode",
        "In-app energy management",
        "Supports solar priority charging",
      ],
    },
  },
  {
    categorySlug: "power-stations",
    manufacturer: "EcoFlow",
    model: "DELTA 2",
    slug: "ecoflow-delta-2",
    summary:
      "1,024 Wh LFP station with 1,800 W AC output, 2,700 W surge, 500 W solar input, and Wi-Fi/Bluetooth control.",
    summaryUk:
      "1,024 Wh LFP station with 1,800 W AC output, 2,700 W surge, 500 W solar input, and Wi-Fi/Bluetooth control.",
    imagePath:
      "https://media.vladyka.dev/power-station/ecoflow/ecoflow-delta-2-portable-power-station-52097645347159.webp",
    priceCents: 59900,
    productCode: "ZMR330-EU",
    nominalVoltageV: 230,
    capacityWh: 1024,
    continuousPowerW: 1800,
    peakPowerW: 2700,
    maxPvVoltageV: 60,
    maxChargeCurrentA: 15,
    chemistry: "LFP",
    communicationProtocols: "Wi-Fi, Bluetooth",
    weightGrams: 12000,
    warrantyYears: 5,
    lifecycleCycles: 3000,
    sourceLabel: "EcoFlow official product page",
    sourceLabelUk: "EcoFlow official product page",
    sourceUrl: "https://eu.ecoflow.com/products/delta-2-portable-power-station",
    specifications: {
      collectionListPosition: 4,
      capacityWh: 1024,
      expandableCapacity: "1-3kWh",
      extraBattery:
        "Supports one DELTA 2 Extra Battery or DELTA Max Extra Battery",
      acOutput: "4 outlets, 1800W total, 2700W surge",
      maxOutputWithXBoostW: 2400,
      maxInputW: 1200,
      acChargingW: 1200,
      solarCharging: "11-60V, 15A, 500W max",
      maxSolarInputW: 500,
      carCharging: "12V/24V battery, 8A",
      dcChargingW: 1100,
      outputPorts: [
        "2 x USB-A 12W",
        "2 x USB-A fast charge 18W",
        "2 x USB-C 100W",
        "Car power 126W",
        "2 x DC5521 38W",
      ],
      dimensionsMm: "400 x 211 x 281",
      netWeightKg: 12,
      packageContents: [
        "DELTA 2",
        "AC charging cable",
        "User manual",
        "App quick start guide",
        "Warranty card",
      ],
      features: [
        "Emergency power supply mode",
        "EcoFlow app control",
        "MPPT solar charging",
      ],
    },
  },
  {
    categorySlug: "power-stations",
    manufacturer: "EcoFlow",
    model: "DELTA 3",
    slug: "ecoflow-delta-3",
    summary:
      "1,024 Wh LFP station with 1,800 W AC output, 3,600 W surge, expandable capacity to 5 kWh, and 5-year warranty.",
    summaryUk:
      "1,024 Wh LFP station with 1,800 W AC output, 3,600 W surge, expandable capacity to 5 kWh, and 5-year warranty.",
    imagePath:
      "https://media.vladyka.dev/power-station/ecoflow/ecoflow-delta-3-series-portable-power-station-60905350299991.webp",
    priceCents: 74900,
    productCode: "EFDELTA3-EU",
    nominalVoltageV: 230,
    capacityWh: 1024,
    continuousPowerW: 1800,
    peakPowerW: 3600,
    maxPvVoltageV: 60,
    chemistry: "LFP",
    communicationProtocols: "EcoFlow app",
    weightGrams: 12500,
    warrantyYears: 5,
    lifecycleCycles: 4000,
    sourceLabel: "EcoFlow official product page",
    sourceLabelUk: "EcoFlow official product page",
    sourceUrl:
      "https://eu.ecoflow.com/products/delta-3-series-portable-power-station",
    specifications: {
      collectionListPosition: 5,
      capacityWh: 1024,
      expandableCapacity: "Up to 5kWh",
      compatibleExtraBatteries: [
        "DELTA 2 Max",
        "DELTA 2",
        "DELTA Pro 3",
        "DELTA 3 Extra Battery",
      ],
      totalOutputPorts: 11,
      acOutlets: 4,
      acOutput: "4 x 1800W, 3600W surge",
      maxOutputWithXBoostW: 2400,
      maxInputW: 1500,
      acCharging: "1500W, 56 minutes",
      solarCharging: "11V-60V, 1 x 500W max",
      maxSolarInputW: 500,
      smartGeneratorCharging: "1500W, 56 minutes",
      carCharging: "800W, 1.3 hours",
      acPlusPvCharging: "1500W, 56 minutes",
      outputPorts: [
        "2 x USB-A fast charge 18W max",
        "2 x USB-C 100W max",
        "Car power 126W",
        "2 x DC5521 12.6V/3A max",
      ],
      dimensionsMm: "398 x 200 x 284",
      extraBatteryDimensionsMm: "398 x 200 x 198",
      upsTransferMs: 10,
      batteryPackWaterproofRating: "IP65",
      noise: ["600W < 30dB", "1200W < 40dB"],
      packageContents: ["DELTA 3"],
      features: [
        "TOU and storm warning app support",
        "Expandable with multiple EcoFlow extra batteries",
        "4000 cycles to 80% capacity",
      ],
    },
  },
];

const nkonBatteryRows: SeedEquipment[] = [
  {
    categorySlug: "batteries",
    manufacturer: "Unbranded",
    model: "51.2V 5kWh 16S 100Ah LiFePO4 Battery Pack - Used",
    slug: "nkon-51-2v-5kwh-16s-100ah-lifepo4-battery-pack-used",
    summary:
      "Used 16S LiFePO4 battery pack from NKON with 51.2 V nominal voltage, 100 Ah capacity, M8 terminals, and 80 A discharge rating.",
    summaryUk:
      "Used 16S LiFePO4 battery pack from NKON with 51.2 V nominal voltage, 100 Ah capacity, M8 terminals, and 80 A discharge rating.",
    imagePath:
      "https://www.nkon.nl/media/catalog/product/cache/d7e8d6be31dedc3e13513f59c64d138b/b/7/b71035b9-9c61-4f32-a230-dbce0def661d.jpeg",
    priceCents: 26495,
    productCode: "NKON-5566",
    nominalVoltageV: 51,
    capacityWh: 5120,
    chemistry: "LiFePO4",
    weightGrams: 51000,
    sourceLabel: "NKON product page",
    sourceLabelUk: "NKON product page",
    sourceUrl:
      "https://www.nkon.nl/novat/5wh-16s-100ah-51-2v-lifepo4-prismatic-battery-in-case.html",
    specifications: {
      listPosition: 1,
      nkonProductId: 5566,
      priceEur: 264.95,
      oldPriceEur: 289.95,
      stockStatus: "Out of stock",
      eanGtin: "6097331978928",
      batteryVersion: "Used",
      grade: "Unknown",
      nominalVoltageV: 51.2,
      seriesCells: 16,
      capacityAh: 100,
      dischargeCurrentA: 80,
      terminalType: "M8",
      dimensionsMm: "460 x 750 x 300",
      heightMm: 460,
      widthMm: 750,
      thicknessMm: 300,
      yearOfProduction: 2020,
      sourceCategoryUrl:
        "https://www.nkon.nl/novat/rechargeable/lifepo4.html?product_list_order=price&product_list_dir=desc",
      additionalImages: [
        "https://www.nkon.nl/media/catalog/product/cache/634f00c0cac7a25d9ea011187773489b/i/m/img_2425.jpg",
        "https://www.nkon.nl/media/catalog/product/cache/634f00c0cac7a25d9ea011187773489b/w/h/whatsapp_image_2024-11-22_at_09.42.04_2_.jpeg",
      ],
    },
  },
  {
    categorySlug: "batteries",
    manufacturer: "Unbranded",
    model:
      "48V 4.7kWh 15S 100Ah LiFePO4 Battery Pack - Used (16S with one broken cell)",
    slug: "nkon-48v-4-7kwh-15s-100ah-lifepo4-battery-pack-used",
    summary:
      "Used LiFePO4 battery pack from NKON listed as a 48 V, 15S, 100 Ah pack; the source notes it was originally 16S with one broken cell.",
    summaryUk:
      "Used LiFePO4 battery pack from NKON listed as a 48 V, 15S, 100 Ah pack; the source notes it was originally 16S with one broken cell.",
    imagePath:
      "https://www.nkon.nl/media/catalog/product/cache/d7e8d6be31dedc3e13513f59c64d138b/b/7/b71035b9-9c61-4f32-a230-dbce0def661d_1.jpeg",
    priceCents: 17995,
    productCode: "NKON-5600",
    nominalVoltageV: 48,
    capacityWh: 4800,
    chemistry: "LiFePO4",
    weightGrams: 51000,
    sourceLabel: "NKON product page",
    sourceLabelUk: "NKON product page",
    sourceUrl:
      "https://www.nkon.nl/novat/48v-4-7kwh-15s-100ah-lifepo4-battery-pack-gebruikt-16s-maar-een-cel-is-kapot.html",
    specifications: {
      listPosition: 2,
      nkonProductId: 5600,
      priceEur: 179.95,
      stockStatus: "Out of stock",
      eanGtin: "6097325994972",
      batteryVersion: "Used",
      grade: "Unknown",
      nominalVoltageV: 48,
      listedEnergyKwh: 4.7,
      seriesCells: 15,
      originalSeriesCells: 16,
      sourceConditionNote: "16S only one cell is broken",
      capacityAh: 100,
      dischargeCurrentA: 80,
      terminalType: "M8",
      dimensionsMm: "0 x 0 x 0",
      sourceCategoryUrl:
        "https://www.nkon.nl/novat/rechargeable/lifepo4.html?product_list_order=price&product_list_dir=desc",
      additionalImages: [
        "https://www.nkon.nl/media/catalog/product/cache/634f00c0cac7a25d9ea011187773489b/i/m/img_2425_1.jpg",
        "https://www.nkon.nl/media/catalog/product/cache/634f00c0cac7a25d9ea011187773489b/w/h/whatsapp_image_2024-10-18_at_10.30.04_1.jpeg",
      ],
    },
  },
  {
    categorySlug: "batteries",
    manufacturer: "EVE",
    model: "MB56 Prismatic 628Ah LiFePO4 3.2V Single Stud - Grade A",
    slug: "nkon-eve-mb56-prismatic-628ah-lifepo4-3-2v-grade-a-single-stud",
    summary:
      "Grade A EVE MB56 prismatic LiFePO4 cell from NKON with 628 Ah capacity, 3.2 V nominal voltage, busbars, and M8 terminal.",
    summaryUk:
      "Grade A EVE MB56 prismatic LiFePO4 cell from NKON with 628 Ah capacity, 3.2 V nominal voltage, busbars, and M8 terminal.",
    imagePath:
      "https://www.nkon.nl/media/catalog/product/cache/d7e8d6be31dedc3e13513f59c64d138b/i/m/image_template_nkon3336_0011_layer_61.jpg",
    priceCents: 11900,
    productCode: "NKON-5847",
    nominalVoltageV: 3,
    capacityWh: 2010,
    chemistry: "LiFePO4",
    weightGrams: 11500,
    sourceLabel: "NKON product page",
    sourceLabelUk: "NKON product page",
    sourceUrl:
      "https://www.nkon.nl/novat/eve-mb56-prismatic-628ah-lifepo4-3-2v-grade-a-single-stud-2.html",
    specifications: {
      listPosition: 3,
      nkonProductId: 5847,
      priceEur: 119,
      stockStatus: "Out of stock",
      eanGtin: "6097335184127",
      grade: "A",
      model: "MB56",
      nominalVoltageV: 3.2,
      capacityAh: 628,
      dischargeCurrentA: 314,
      included: "Busbars",
      terminalType: "M8",
      dimensionsMm: "205.1 x 352.3 x 71.7",
      heightMm: 205.1,
      widthMm: 352.3,
      thicknessMm: 71.7,
      sourceCategoryUrl:
        "https://www.nkon.nl/novat/rechargeable/lifepo4.html?product_list_order=price&product_list_dir=desc",
      additionalImages: [
        "https://www.nkon.nl/media/catalog/product/cache/634f00c0cac7a25d9ea011187773489b/i/m/image_template_nkon3336_0008_layer_64.jpg",
        "https://www.nkon.nl/media/catalog/product/cache/634f00c0cac7a25d9ea011187773489b/i/m/image_template_nkon3336_0010_layer_62.jpg",
      ],
    },
  },
  {
    categorySlug: "batteries",
    manufacturer: "EVE",
    model: "MB56 Prismatic 628Ah LiFePO4 3.2V Single Stud - Grade A-",
    slug: "nkon-eve-mb56-prismatic-628ah-lifepo4-3-2v-grade-a-minus-single-stud",
    summary:
      "Grade A- EVE MB56 prismatic LiFePO4 cell from NKON with 628 Ah capacity, 3.2 V nominal voltage, busbars, and M8 terminal.",
    summaryUk:
      "Grade A- EVE MB56 prismatic LiFePO4 cell from NKON with 628 Ah capacity, 3.2 V nominal voltage, busbars, and M8 terminal.",
    imagePath:
      "https://www.nkon.nl/media/catalog/product/cache/d7e8d6be31dedc3e13513f59c64d138b/m/b/mb56_3_.jpg",
    priceCents: 10995,
    productCode: "NKON-5846",
    nominalVoltageV: 3,
    capacityWh: 2010,
    chemistry: "LiFePO4",
    weightGrams: 11500,
    sourceLabel: "NKON product page",
    sourceLabelUk: "NKON product page",
    sourceUrl:
      "https://www.nkon.nl/novat/eve-mb56-prismatic-628ah-lifepo4-3-2v-grade-a-single-stud.html",
    specifications: {
      listPosition: 4,
      nkonProductId: 5846,
      priceEur: 109.95,
      stockStatus: "In stock",
      eanGtin: "6097335184127",
      grade: "A-",
      model: "MB56",
      nominalVoltageV: 3.2,
      capacityAh: 628,
      dischargeCurrentA: 314,
      included: "Busbars",
      terminalType: "M8",
      dimensionsMm: "205.1 x 352.3 x 71.7",
      heightMm: 205.1,
      widthMm: 352.3,
      thicknessMm: 71.7,
      sourceCategoryUrl:
        "https://www.nkon.nl/novat/rechargeable/lifepo4.html?product_list_order=price&product_list_dir=desc",
      additionalImages: [
        "https://www.nkon.nl/media/catalog/product/cache/634f00c0cac7a25d9ea011187773489b/_/_/__20260309191347.jpg",
        "https://www.nkon.nl/media/catalog/product/cache/634f00c0cac7a25d9ea011187773489b/w/h/whatsapp_image_2025-09-03_at_10.11.57_1.jpeg",
      ],
    },
  },
  {
    categorySlug: "batteries",
    manufacturer: "REPT",
    model: "7x CB3914895EA 50Ah LiFePO4 3.2V - Grade A",
    slug: "nkon-7x-rept-cb3914895ea-50ah-lifepo4-3-2v-grade-a",
    summary:
      "NKON listing for seven REPT CB3914895EA Grade A LiFePO4 cells, each rated at 50 Ah and 3.2 V.",
    summaryUk:
      "NKON listing for seven REPT CB3914895EA Grade A LiFePO4 cells, each rated at 50 Ah and 3.2 V.",
    imagePath:
      "https://www.nkon.nl/media/catalog/product/cache/d7e8d6be31dedc3e13513f59c64d138b/i/m/image_template_nkon3334_0016_layer_153_2.jpg",
    priceCents: 9000,
    productCode: "NKON-5728",
    nominalVoltageV: 3,
    capacityWh: 1120,
    chemistry: "LiFePO4",
    weightGrams: 8050,
    sourceLabel: "NKON product page",
    sourceLabelUk: "NKON product page",
    sourceUrl:
      "https://www.nkon.nl/novat/1x-rept-battero-72174l4-280ah-prismatic-280ah-lifepo4-3-2v-grade-a.html",
    specifications: {
      listPosition: 5,
      nkonProductId: 5728,
      priceEur: 90,
      stockStatus: "Out of stock",
      cellCount: 7,
      cellModel: "CB3914895EA",
      grade: "A",
      nominalVoltageV: 3.2,
      cellCapacityAh: 50,
      estimatedPackEnergyWh: 1120,
      sourceCategoryUrl:
        "https://www.nkon.nl/novat/rechargeable/lifepo4.html?product_list_order=price&product_list_dir=desc",
    },
  },
];

const seededEquipmentRows = [
  ...ankerPowerBankRows,
  ...ugreenPowerBankRows,
  ...equipmentRows.filter(
    (row) =>
      !["power-banks", "batteries", "power-stations", "inverters"].includes(
        row.categorySlug,
      ),
  ),
  ...victronInverterRows,
  ...ecoFlowPowerStationRows,
  ...nkonBatteryRows,
];

async function upsertCategories() {
  for (const row of categories) {
    await db
      .insert(equipmentCategories)
      .values(row)
      .onConflictDoUpdate({
        target: equipmentCategories.slug,
        set: {
          name: row.name,
          nameUk: row.nameUk,
          description: row.description,
          descriptionUk: row.descriptionUk,
        },
      });
  }
}

async function upsertManufacturers() {
  for (const row of manufacturerRows) {
    await db
      .insert(manufacturers)
      .values(row)
      .onConflictDoUpdate({
        target: manufacturers.name,
        set: {
          country: row.country,
        },
      });
  }
}

async function seedEquipment() {
  const categoryRows = await db.select().from(equipmentCategories);
  const manufacturerRecords = await db.select().from(manufacturers);

  const categoryIds = new Map(categoryRows.map((row) => [row.slug, row.id]));
  const manufacturerIds = new Map(
    manufacturerRecords.map((row) => [row.name, row.id]),
  );
  const resetCategoryIds = [
    "power-banks",
    "power-stations",
    "batteries",
    "inverters",
  ]
    .map((slug) => categoryIds.get(slug))
    .filter((id): id is number => id !== undefined);

  for (const categoryId of resetCategoryIds) {
    await db.delete(equipment).where(eq(equipment.categoryId, categoryId));
  }

  for (const row of seededEquipmentRows) {
    const categoryId = categoryIds.get(row.categorySlug);
    const manufacturerId = manufacturerIds.get(row.manufacturer);

    if (!categoryId || !manufacturerId) {
      throw new Error(`Missing seed relation for ${row.slug}`);
    }

    await db
      .insert(equipment)
      .values({
        categoryId,
        manufacturerId,
        slug: row.slug,
        model: row.model,
        summary: row.summary,
        summaryUk: row.summaryUk,
        imagePath: row.imagePath,
        priceCents: row.priceCents ?? null,
        productCode: row.productCode ?? null,
        nominalVoltageV: row.nominalVoltageV ?? null,
        capacityWh: row.capacityWh ?? null,
        continuousPowerW: row.continuousPowerW ?? null,
        peakPowerW: row.peakPowerW ?? null,
        maxPvVoltageV: row.maxPvVoltageV ?? null,
        maxChargeCurrentA: row.maxChargeCurrentA ?? null,
        chemistry: row.chemistry ?? null,
        communicationProtocols: row.communicationProtocols ?? null,
        weightGrams: row.weightGrams ?? null,
        warrantyYears: row.warrantyYears ?? null,
        lifecycleCycles: row.lifecycleCycles ?? null,
        sourceLabel: row.sourceLabel,
        sourceLabelUk: row.sourceLabelUk,
        sourceUrl: row.sourceUrl ?? null,
        specifications: row.specifications ?? null,
      })
      .onConflictDoUpdate({
        target: equipment.slug,
        set: {
          summary: row.summary,
          summaryUk: row.summaryUk,
          imagePath: row.imagePath,
          priceCents: row.priceCents ?? null,
          productCode: row.productCode ?? null,
          nominalVoltageV: row.nominalVoltageV ?? null,
          capacityWh: row.capacityWh ?? null,
          continuousPowerW: row.continuousPowerW ?? null,
          peakPowerW: row.peakPowerW ?? null,
          maxPvVoltageV: row.maxPvVoltageV ?? null,
          maxChargeCurrentA: row.maxChargeCurrentA ?? null,
          chemistry: row.chemistry ?? null,
          communicationProtocols: row.communicationProtocols ?? null,
          weightGrams: row.weightGrams ?? null,
          warrantyYears: row.warrantyYears ?? null,
          lifecycleCycles: row.lifecycleCycles ?? null,
          sourceLabel: row.sourceLabel,
          sourceLabelUk: row.sourceLabelUk,
          sourceUrl: row.sourceUrl ?? null,
          specifications: row.specifications ?? null,
          updatedAt: new Date(),
        },
      });
  }
}

async function main() {
  await upsertCategories();
  await upsertManufacturers();
  await seedEquipment();

  const [{ seededRows }] = await db
    .select({ seededRows: count() })
    .from(equipment);

  console.log(`Seeded catalog mock data. Total product rows: ${seededRows}`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await postgresClient.end();
  });
