import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";
import SiteFooter from "@/app/_components/site-footer";
import SiteHeader from "@/app/_components/site-header";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const themeScript = `
(() => {
  const storageKey = "powerbase-theme";
  const validThemes = new Set(["system", "light", "dark"]);

  const getPreference = () => {
    try {
      const storedTheme = window.localStorage.getItem(storageKey);
      return validThemes.has(storedTheme) ? storedTheme : "system";
    } catch {
      return "system";
    }
  };

  const preference = getPreference();
  const prefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
  const resolvedTheme = preference === "system" ? (prefersDark ? "dark" : "light") : preference;
  const root = document.documentElement;

  root.classList.toggle("dark", resolvedTheme === "dark");
  root.dataset.theme = preference;
  root.style.colorScheme = resolvedTheme;
})();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn("font-sans", geist.variable)}
    >
      <body className="antialiased">
        <Script
          id="powerbase-theme"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{ __html: themeScript }}
        />
        <div className="mx-auto flex min-h-screen max-w-[1440px] flex-col">
          <SiteHeader />
          <main className="flex-1">{children}</main>
          <SiteFooter />
        </div>
      </body>
    </html>
  );
}
