import type { Metadata } from "next";
import "./globals.css";
import SiteFooter from "@/app/_components/site-footer";
import SiteHeader from "@/app/_components/site-header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const themeScript = `
(() => {
  const darkThemeColor = "#09090b";
  const lightThemeColor = "#ffffff";

  try {
    const storedTheme = localStorage.getItem("theme");
    const prefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
    const isSystemTheme = storedTheme !== "light" && storedTheme !== "dark";
    const isDark = storedTheme === "dark" || (isSystemTheme && prefersDark);
    const themeColor = document.querySelector('meta[name="theme-color"]');

    document.documentElement.classList.toggle("dark", isDark);
    document.documentElement.dataset.theme = isDark ? "dark" : "light";
    document.documentElement.style.colorScheme = isDark ? "dark" : "light";

    if (themeColor) {
      themeColor.setAttribute("content", isDark ? darkThemeColor : lightThemeColor);
    }
  } catch (_) {}
})();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="font-sans"
    >
      <head>
        <meta name="theme-color" content="#ffffff" />
        <script
          id="powerbase-theme"
          dangerouslySetInnerHTML={{ __html: themeScript }}
        />
      </head>
      <body className="antialiased">
        <div className="mx-auto flex min-h-screen max-w-[1440px] flex-col">
          <SiteHeader />
          <main className="flex-1">{children}</main>
          <SiteFooter />
        </div>
      </body>
    </html>
  );
}
